### ISSUE TITLE
"IndexError: list index out of range"

### ISSUE THREAD

**Issue by Wolfsrudel** [ShahriyarR/MySQL-AutoXtraBackup#1]
```
[root@c-two-mysql MySQL-AutoXtraBackup]# autoxtrabackup --help
Usage: autoxtrabackup [OPTIONS]

Options:
  --prepare  Prepare/recover backups.
  --backup   Take full and incremental backups.
  --partial  Recover specified table (partial recovery).
  --version  Version information.
  --help     Show this message and exit.

[root@c-two-mysql MySQL-AutoXtraBackup]# autoxtrabackup --backup
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.4.3/bin/autoxtrabackup", line 9, in <module>
    load_entry_point('mysql-autoxtrabackup==1.0', 'console_scripts', 'autoxtrabackup')()
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/mysql_autoxtrabackup-1.0-py3.4.egg/autoxtrabackup.py", line 34, in all_procedure
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/mysql_autoxtrabackup-1.0-py3.4.egg/master_backup_script/backuper.py", line 25, in __init__
  File "/root/.pyenv/versions/3.4.3/lib/python3.4/site-packages/mysql_autoxtrabackup-1.0-py3.4.egg/general_conf/generalops.py", line 13, in __init__
IndexError: list index out of range
```

Same error with Python 3.3.2.

**Comment by ShahriyarR** [comment]
Thank you for testing.

For me on CentOS 7 
With  Python 3.3.2 :

    [root@centos7 MySQL-AutoXtraBackup]# autoxtrabackup --help
    Usage: autoxtrabackup [OPTIONS]

    Options:
    --prepare  Prepare/recover backups.
    --backup   Take full and incremental backups.
    --partial  Recover specified table (partial recovery).
    --version  Version information.
    --help     Show this message and exit.
    [root@centos7 MySQL-AutoXtraBackup]# autoxtrabackup --backup
    Warning: Using a password on the command line interface can be insecure.
    Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
    /usr/bin/mysql exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-OK
    /usr/bin/mysqladmin exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
    MySQL configuration file path does NOT exist+-+-+-+-+-+-+-+-+-+
    Check status: STATUS+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-FAILED


And with Python 3.4.2:

    [root@centos7 MySQL-AutoXtraBackup]# /opt/python3.4/bin/autoxtrabackup --backup
    Warning: Using a password on the command line interface can be insecure.
    Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
    /usr/bin/mysql exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-OK
    /usr/bin/mysqladmin exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
    MySQL configuration file path does NOT exist+-+-+-+-+-+-+-+-+-+
    Check status: STATUS+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-FAILED


Did you follow steps from README?

**Comment by ShahriyarR** [comment]
Even with 3.4.3 it is working, maybe it is related to pyenv, i will check it too:

    [root@centos7 MySQL-AutoXtraBackup]# /opt/python3.4.3/bin/autoxtrabackup --backup
    Warning: Using a password on the command line interface can be insecure.
    Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
    /usr/bin/mysql exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-OK
    /usr/bin/mysqladmin exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
    MySQL configuration file path does NOT exist+-+-+-+-+-+-+-+-+-+
    Check status: STATUS+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-FAILED

**Comment by ShahriyarR** [comment]
@Wolfsrudel -> from your issue, i found that, if we put MySQL-AutoXtrabackup project to /home folder there will not be an error as i described. 
But if we put it in other place say into the /root folder:

    root@centos7 ~]# autoxtrabackup --backup
    Traceback (most recent call last):
      File "/usr/local/bin/autoxtrabackup", line 9, in <module>
        load_entry_point('mysql-autoxtrabackup==1.0', 'console_scripts', 'autoxtrabackup')()
      File "/usr/local/lib/python3.3/site-packages/click-4.0-py3.3.egg/click/core.py", line 664, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.3/site-packages/click-4.0-py3.3.egg/click/core.py", line 644, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.3/site-packages/click-4.0-py3.3.egg/click/core.py", line 837, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.3/site-packages/click-4.0-py3.3.egg/click/core.py", line 464, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python3.3/site-packages/mysql_autoxtrabackup-1.0-py3.3.egg    /autoxtrabackup.py", line 34, in all_procedure
      File "/usr/local/lib/python3.3/site-packages/mysql_autoxtrabackup-1.0-py3.3.egg/master_backup_script/backuper.py", line 25, in __init__
      File "/usr/local/lib/python3.3/site-packages/mysql_autoxtrabackup-1.0-py3.3.egg/general_conf/generalops.py", line 13, in __init__
    IndexError: list index out of range

**Comment by ShahriyarR** [comment]
Issue description:
Due to configuration file path, trying to run command from non-project folder will rise exception, shown above.
Fixed as:
From now there is a global readable '/etc/bck.conf' config file.

**Comment by Wolfsrudel** [comment]
Thanks a lot! I'll test it. :)

**Comment by ShahriyarR** [comment]
:) waiting for new issues )
