### ISSUE TITLE
Call preparing environment and sysbench run when --test_mode is enabled

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#101]
The previously added features should be called safely from main run script `autoxtrabackup`.
To keep in mind that, `--test_mode` is mutually exclusive with most of the options.
So basically if --test_mode option specified even other options are specified, isolate it.

**Comment by ShahriyarR** [comment]
Failed with:

```
$ autoxtrabackup --help
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.8', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/autoxtrabackup.py", line 6, in <module>
ImportError: No module named 'prepare_env_test_mode'
```

**Comment by ShahriyarR** [comment]
Nice --help:

```
$ autoxtrabackup --help
Usage: autoxtrabackup [OPTIONS]

Options:
  --dry_run                       Enable the dry run.
  --prepare                       Prepare/recover backups.
  --backup                        Take full and incremental backups.
  --partial                       Recover specified table (partial recovery).
  --version                       Version information.
  --defaults_file TEXT            Read options from the given file
  -v, --verbose                   Be verbose (print to console)
  -l, --log [DEBUG|INFO|WARNING|ERROR|CRITICAL]
                                  Set log level
  --test_mode                     Enable test mode.[It will clone, build,
                                  start the PS server, take backup, prepare
                                  and recover]
  --help                          Show this message and exit.
```

**Comment by ShahriyarR** [comment]
Failed with:

```
$ autoxtrabackup --test_mode -l DEBUG
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.8', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/autoxtrabackup.py", line 162, in all_procedure
TypeError: all_runner() missing 1 required positional argument: 'self'
```

**Comment by ShahriyarR** [comment]
Another fail here:

```
$ autoxtrabackup --test_mode -l DEBUG -v
2017-10-08 22:01:24 DEBUG    <pid.PidFile object at 0x7f6cae80cb88> entering setup
2017-10-08 22:01:24 DEBUG    <pid.PidFile object at 0x7f6cae80cb88> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-10-08 22:01:24 DEBUG    <pid.PidFile object at 0x7f6cae80cb88> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-10-08 22:01:24 WARNING  Enabled Test Mode
2017-10-08 22:01:24 DEBUG    Starting Test Mode
2017-10-08 22:01:24 DEBUG    Could get PS basedir path returning...
2017-10-08 22:01:29 ERROR    All script run failed
2017-10-08 22:01:29 ERROR    /home/shahriyar.rzaev/XB_TEST/server_dir/PS081017-percona-server-5.7.19-17-linux-x86_64-debug/all: line 1: ./wipe: No such file or directory
/home/shahriyar.rzaev/XB_TEST/server_dir/PS081017-percona-server-5.7.19-17-linux-x86_64-debug/all: line 1: ./start: No such file or directory
/home/shahriyar.rzaev/XB_TEST/server_dir/PS081017-percona-server-5.7.19-17-linux-x86_64-debug/all: line 1: ./cl: No such file or directory
2017-10-08 22:01:29 DEBUG    <pid.PidFile object at 0x7f6cae80cb88> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-10-08 22:01:29 DEBUG    <pid.PidFile object at 0x7f6cae80cb88> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

The thing maybe related to wipe script itself because it needs to be run inside the basedir.
The possible workaround:
1. Change the working dir to basedir.
2. Call all related scripts directly, i.e not using `all` script but manually running `wipe` etc.

**Comment by ShahriyarR** [comment]
The `all` script has some problems which is blocking to complete this issue.

Please see:

https://github.com/Percona-QA/percona-qa/issues/229

**Comment by ShahriyarR** [comment]
New fail:

```
$ autoxtrabackup --test_mode -l DEBUG -v
2017-10-09 10:13:13 DEBUG    <pid.PidFile object at 0x7f7f80d1db88> entering setup
2017-10-09 10:13:13 DEBUG    <pid.PidFile object at 0x7f7f80d1db88> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-10-09 10:13:13 DEBUG    <pid.PidFile object at 0x7f7f80d1db88> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-10-09 10:13:13 WARNING  Enabled Test Mode!!!
2017-10-09 10:13:13 DEBUG    Starting Test Mode
2017-10-09 10:13:13 DEBUG    Test dir does not exist
2017-10-09 10:13:13 DEBUG    Creating test mode directory
2017-10-09 10:13:13 ERROR    Could not get PS basedir path failed...
2017-10-09 10:13:13 ERROR    ls: cannot access /home/shahriyar.rzaev/XB_TEST/server_dir/PS*: No such file or directory
2017-10-09 10:13:13 DEBUG    <pid.PidFile object at 0x7f7f80d1db88> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.8', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/autoxtrabackup.py", line 162, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 14, in all_runner
TypeError: argument of type 'bool' is not iterable
2017-10-09 10:13:13 DEBUG    <pid.PidFile object at 0x7f7f80d1db88> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

**Comment by ShahriyarR** [comment]
```
$ autoxtrabackup --test_mode -l DEBUG -v
2017-10-09 10:33:22 DEBUG    <pid.PidFile object at 0x7f1efa22ab88> entering setup
2017-10-09 10:33:22 DEBUG    <pid.PidFile object at 0x7f1efa22ab88> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-10-09 10:33:22 DEBUG    <pid.PidFile object at 0x7f1efa22ab88> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-10-09 10:33:22 WARNING  Enabled Test Mode!!!
2017-10-09 10:33:22 DEBUG    Starting Test Mode
2017-10-09 10:33:22 WARNING  Could not get PS basedir path failed...
2017-10-09 10:33:55 DEBUG    percona-qa ready to use
2017-10-09 10:34:25 DEBUG    PS cloned ready to build
2017-10-09 11:11:47 DEBUG    PS build succeeded
2017-10-09 11:11:47 DEBUG    <pid.PidFile object at 0x7f1efa22ab88> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.8', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/autoxtrabackup.py", line 162, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 24, in all_runner
TypeError: prepare_startup() missing 1 required positional argument: 'basedir_path'
2017-10-09 11:11:47 DEBUG    <pid.PidFile object at 0x7f1efa22ab88> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

**Comment by ShahriyarR** [comment]
```
$ autoxtrabackup --test_mode -l DEBUG -v
2017-10-09 11:30:22 DEBUG    <pid.PidFile object at 0x7f259ccd2e08> entering setup
2017-10-09 11:30:22 DEBUG    <pid.PidFile object at 0x7f259ccd2e08> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-10-09 11:30:22 DEBUG    <pid.PidFile object at 0x7f259ccd2e08> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-10-09 11:30:22 WARNING  Enabled Test Mode!!!
2017-10-09 11:30:22 DEBUG    Starting Test Mode
2017-10-09 11:30:22 DEBUG    Test dir does not exist
2017-10-09 11:30:22 DEBUG    Creating test mode directory
2017-10-09 11:30:22 WARNING  Could not get PS basedir path...
2017-10-09 11:30:53 DEBUG    percona-qa ready to use
2017-10-09 11:31:21 DEBUG    PS cloned ready to build
2017-10-09 12:08:45 DEBUG    PS build succeeded
2017-10-09 12:08:45 WARNING  Could not get PS basedir path...
2017-10-09 12:08:45 DEBUG    <pid.PidFile object at 0x7f259ccd2e08> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.8', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/autoxtrabackup.py", line 162, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 25, in all_runner
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/prepare_env_test_mode/clone_build_start_server.py", line 94, in prepare_startup
NotADirectoryError: [Errno 20] Not a directory: False
2017-10-09 12:08:45 DEBUG    <pid.PidFile object at 0x7f259ccd2e08> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

**Comment by ShahriyarR** [comment]
Finally it is implemented:

```
$ autoxtrabackup --test_mode -l DEBUG -vvv
2017-10-09 18:10:54 DEBUG    <pid.PidFile object at 0x7ff63e636e08> entering setup
2017-10-09 18:10:54 DEBUG    <pid.PidFile object at 0x7ff63e636e08> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-10-09 18:10:54 DEBUG    <pid.PidFile object at 0x7ff63e636e08> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-10-09 18:10:54 WARNING  Enabled Test Mode!!!
2017-10-09 18:10:54 DEBUG    Starting Test Mode
2017-10-09 18:10:54 DEBUG    Trying to get basedir path...
2017-10-09 18:10:54 DEBUG    Could get PS basedir path returning...
2017-10-09 18:12:02 DEBUG    Using all_no_cl script here...
2017-10-09 18:12:02 DEBUG    Server wiped for fresh start!
2017-10-09 18:12:02 DEBUG    Trying to get basedir path...
2017-10-09 18:12:02 DEBUG    Could get PS basedir path returning...
2017-10-09 18:12:02 DEBUG    Here is the mysql client!
2017-10-09 18:12:02 DEBUG    Given DB is created!
2017-10-09 18:13:43 DEBUG    Sysbench succeeded!
2017-10-09 18:13:43 DEBUG    <pid.PidFile object at 0x7ff63e636e08> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-10-09 18:13:43 DEBUG    <pid.PidFile object at 0x7ff63e636e08> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```
