### ISSUE TITLE
Implement taking backup in --test_mode

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#103]
As described in #99 and #101 we have implemented the server setup/benchmark run things.
And now it is turn of taking backup.

We have this module, but it seems to be it needs some modifications.

**Comment by ShahriyarR** [comment]
```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/_pytest/config.py", line 379, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/shahriyar.rzaev/MySQL-AutoXtraBackup/test/conftest.py", line 35, in <module>
    bck_obj = WrapperForBackupTest()
  File "/home/shahriyar.rzaev/MySQL-AutoXtraBackup/prepare_env_test_mode/take_backup.py", line 8, in __init__
    super().__init__(config="{}/xb_2_4.conf".format(self.testpath))
  File "/home/shahriyar.rzaev/MySQL-AutoXtraBackup/master_backup_script/backuper.py", line 36, in __init__
    GeneralClass.__init__(self, self.conf)
  File "/home/shahriyar.rzaev/MySQL-AutoXtraBackup/general_conf/generalops.py", line 39, in __init__
    self.tmpdir = BCK['tmpdir']
  File "/home/shahriyar.rzaev/Python_interpreters/Python_3_5_3/lib/python3.5/configparser.py", line 1230, in __getitem__
    raise KeyError(key)
KeyError: 'tmpdir'
ERROR: could not load /home/shahriyar.rzaev/MySQL-AutoXtraBackup/test/conftest.py
```

**Comment by ShahriyarR** [comment]
```
=============================================================================== FAILURES ================================================================================
__________________________________________________________________ TestTakeBackup.test_run_all_backup ___________________________________________________________________

self = <test.test_take_backup.TestTakeBackup object at 0x7f81e4d0b828>
return_take_backup_obj = <prepare_env_test_mode.take_backup.WrapperForBackupTest object at 0x7f81e4dac898>

    def test_run_all_backup(self, return_take_backup_obj):
>       return_take_backup_obj.run_all_backup()

test/test_take_backup.py:8: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
prepare_env_test_mode/take_backup.py:16: in run_all_backup
    self.backup_obj.all_backup()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <master_backup_script.backuper.Backup object at 0x7f81e587d9e8>

    def all_backup(self):
        """
             This function at first checks full backup directory, if it is empty takes full backup.
             If it is not empty then checks for full backup time.
             If the recent full backup  is taken 1 day ago, it takes full backup.
             In any other conditions it takes incremental backup.
            """
        # Workaround for circular import dependency error in Python
    
        # Creating object from CheckEnv class
        check_env_obj = CheckEnv(self.conf)
    
        if check_env_obj.check_all_env():
    
            if self.recent_full_backup_file() == 0:
                logger.debug(
                    "###############################################################")
                logger.debug(
                    "#You have no backups : Taking very first Full Backup! - - - - #")
                logger.debug(
                    "###############################################################")
    
                time.sleep(3)
    
                # Flushing Logs
                if self.mysql_connection_flush_logs():
    
                    # Taking fullbackup
                    if self.full_backup():
                        # Removing old inc backups
                        self.clean_inc_backup_dir()
    
                # Copying backups to remote server
                if hasattr(
                        self,
                        'remote_conn') and hasattr(
                        self,
                        'remote_dir') and self.remote_conn and self.remote_dir:
                    self.copy_backup_to_remote_host()
    
                # Exiting after taking full backup
>               exit(0)
E               SystemExit: 0

master_backup_script/backuper.py:680: SystemExit

```

It seems to be wrong config file options were generated

**Comment by ShahriyarR** [comment]
And it seems to be worked, already.
But the problem is it is not incrementing over incremental backups, it seems to be sys.exit() usage.

```
$ python -m pytest -s -vvv ~/MySQL-AutoXtraBackup/test/test_take_backup.py::TestTakeBackup::test_run_all_backup
========================================================================== test session starts ==========================================================================
platform linux -- Python 3.5.3, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/python
cachedir: .cache
rootdir: /home/shahriyar.rzaev/MySQL-AutoXtraBackup, inifile:
collected 1 item                                                                                                                                                         

test/test_take_backup.py::TestTakeBackup::test_run_all_backup mysqladmin: [Warning] Using a password on the command line interface can be insecure.
PASSED
```

**Comment by ShahriyarR** [comment]
So as a result it took, 1 full and 3 incremental backups here:

```
$ python -m pytest -s -vvv ~/MySQL-AutoXtraBackup/test/test_take_backup.py::TestTakeBackup::test_run_all_backup
========================================================================== test session starts ==========================================================================
platform linux -- Python 3.5.3, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/python
cachedir: .cache
rootdir: /home/shahriyar.rzaev/MySQL-AutoXtraBackup, inifile:
collected 1 item                                                                                                                                                         

test/test_take_backup.py::TestTakeBackup::test_run_all_backup mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
PASSED
```
