### ISSUE TITLE
Make possible to create backup from master and start slave from this backup for --test_mode

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#144]
This feature is needed for --test_mode.
The idea is, to take backup, then prepare this backup and start slave server if it is started properly + check consistency between master and slave.

**Comment by ShahriyarR** [comment]
Related issue:
https://github.com/Percona-QA/percona-qa/issues/241

**Comment by ShahriyarR** [comment]
```
2017-10-30 11:38:10 ERROR    pt-table-checksum command failed
2017-10-30 11:38:10 ERROR    Diffs cannot be detected because no slaves were found.  Please read the --recursion-method documentation for information.
            TS ERRORS  DIFFS     ROWS  CHUNKS SKIPPED    TIME TABLE
10-30T11:37:49      0      0        0       1       0   0.093 mysql.columns_priv
10-30T11:37:49      0      0        2       1       0   0.124 mysql.db
10-30T11:37:49      0      0        0       1       0   0.088 mysql.event
10-30T11:37:49      0      0        0       1       0   0.090 mysql.func
10-30T11:37:50      0      0       40       4       0   0.413 mysql.help_category
10-30T11:37:50      0      0      615       4       0   0.406 mysql.help_keyword
10-30T11:37:50      0      0     1253       1       0   0.106 mysql.help_relation
10-30T11:37:50      0      0      585       1       0   0.096 mysql.help_topic
10-30T11:37:50      0      0        0       1       0   0.090 mysql.ndb_binlog_index
```

**Comment by ShahriyarR** [comment]
The last thing in this feature is to make slave to work :)

```
2017-10-30 21:21:43 DEBUG    <pid.PidFile object at 0x7f6f456c0408> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.9', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.9-py3.5.egg/autoxtrabackup.py", line 169, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.9-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 257, in wipe_backup_prepare_copyback
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.9-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 173, in run_change_master
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.9-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 110, in check_slave_status
RuntimeError: Slave_IO_Running is not Yes
2017-10-30 21:21:43 DEBUG    <pid.PidFile object at 0x7f6f456c0408> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

**Comment by ShahriyarR** [comment]
I think I should run `SET GLOBAL gtid_purged=` prior running `CHANGE MASTER`

**Comment by ShahriyarR** [comment]
After fighting with several issues, Now it is fully implemented.

**Comment by ShahriyarR** [comment]
```
2017-10-31 14:50:05 DEBUG    Started to make this new server as slave...
2017-10-31 14:50:05 DEBUG    Trying to get basedir path...
2017-10-31 14:50:05 DEBUG    Could get PS basedir path returning...
2017-10-31 14:50:05 DEBUG    Trying to get mysql client connection...
2017-10-31 14:50:05 DEBUG    Could get mysql client
2017-10-31 14:50:05 DEBUG    Trying to get basedir path...
2017-10-31 14:50:05 DEBUG    Could get PS basedir path returning...
2017-10-31 14:50:05 DEBUG    Trying to get mysql client connection...
2017-10-31 14:50:05 DEBUG    Could get mysql client
2017-10-31 14:50:05 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/socket.sock --force test -e 'select @@port'
2017-10-31 14:50:05 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/socket.sock --force test -e "CREATE USER 'repl'@'%' IDENTIFIED BY 'Baku12345'"
2017-10-31 14:50:05 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/socket.sock --force test -e "GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%'"
2017-10-31 14:50:05 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/socket.sock --force test -e "select user, host from mysql.user where user like ''"
2017-10-31 14:50:05 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/socket.sock --force test -e "select user, host from mysql.user where user like ''"
2017-10-31 14:50:05 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/socket.sock --force test -e "drop user ''@'localhost'"
2017-10-31 14:50:05 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/socket.sock --force test -e "drop user ''@'localhost'"
2017-10-31 14:50:05 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/socket.sock --force test -e "drop user ''@'qaserver-02.ci.percona.com'"
2017-10-31 14:50:05 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/socket.sock --force test -e "drop user ''@'qaserver-02.ci.percona.com'"
2017-10-31 14:50:05 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/sock0.sock --force test -e 'set global gtid_purged="a3b124ec-be49-11e7-b106-002590e9b448:1-42584"'
2017-10-31 14:50:06 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/sock0.sock --force test -e "CHANGE MASTER TO MASTER_HOST='127.0.0.1', MASTER_USER='repl', MASTER_PASSWORD='Baku12345', MASTER_PORT=15196, MASTER_AUTO_POSITION=1"
2017-10-31 14:50:06 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/sock0.sock --force test -e 'start slave'
2017-10-31 14:50:26 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/sock0.sock --force test -e 'show slave status\G'
2017-10-31 14:50:26 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/socket.sock --force test -e 'CREATE TABLE `dsns` (
                          `id` int(11) NOT NULL AUTO_INCREMENT,
                          `parent_id` int(11) DEFAULT NULL,
                          `dsn` varchar(255) NOT NULL,
                          PRIMARY KEY (`id`))
                        '
2017-10-31 14:50:26 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/sock0.sock --force test -e 'select @@port'
2017-10-31 14:50:26 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.6.37-82.2-linux-x86_64-debug/socket.sock --force test -e 'insert into dsns(id, parent_id, dsn) values(30, 84, "h=127.0.0.1,u=root,P=58135")'
2017-10-31 14:50:36 DEBUG    Trying to get basedir path...
2017-10-31 14:50:37 DEBUG    Could get PS basedir path returning...
2017-10-31 14:50:37 DEBUG    Trying to get socket file...
2017-10-31 14:51:32 DEBUG    pt-table-checksum succeeded on master
```

**Comment by ShahriyarR** [comment]
Merged to release_v1.5.0.
Closing.
