### ISSUE TITLE
RuntimeError: Failed to run SQL command -> ERROR 1840 (HY000) at line 1: @@GLOBAL.GTID_PURGED can only be set when @@GLOBAL.GTID_EXECUTED is empty.

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#157]
```
2017-11-02 14:22:56 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/sock0.sock --force test -e 'set global gtid_purged="c88e0107-bfd6-11e7-9a8f-002590e9b448:1-11199"'
2017-11-02 14:22:56 DEBUG    <pid.PidFile object at 0x7fb6585c9ea8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.9', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.9-py3.5.egg/autoxtrabackup.py", line 177, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.9-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 332, in wipe_backup_prepare_copyback
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.9-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 228, in run_change_master
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.9-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 133, in run_sql_command
RuntimeError: Failed to run SQL command -> ERROR 1840 (HY000) at line 1: @@GLOBAL.GTID_PURGED can only be set when @@GLOBAL.GTID_EXECUTED is empty.
2017-11-02 14:22:56 DEBUG    <pid.PidFile object at 0x7fb6585c9ea8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

**Comment by ShahriyarR** [comment]
It seems that, It requires to run `reset master` on slave before executing `set gtid_purged`.

It is described here:
https://avdeo.com/tag/error-1840-hy000-global-gtid_purged-can-only-be-set-when/

And here:
https://www.percona.com/blog/2013/02/08/how-to-createrestore-a-slave-using-gtid-replication-in-mysql-5-6/

**Comment by ShahriyarR** [comment]
Now it seems to be fixed:

```
2017-11-02 18:43:29 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/socket.sock --force test -e 'select @@port'
2017-11-02 18:44:42 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/socket.sock --force test -e "CREATE USER 'repl'@'%' IDENTIFIED BY 'Baku12345'"
2017-11-02 18:44:46 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/socket.sock --force test -e "GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%'"
2017-11-02 18:45:09 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/sock0.sock --force test -e 'reset master'
2017-11-02 18:45:33 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/sock0.sock --force test -e 'set global gtid_purged="b6d999db-bff9-11e7-a3cc-002590e9b448:1-11822"'
2017-11-02 18:45:44 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/sock0.sock --force test -e "CHANGE MASTER TO MASTER_HOST='127.0.0.1', MASTER_USER='repl', MASTER_PASSWORD='Baku12345', MASTER_PORT=16584, MASTER_AUTO_POSITION=1"
2017-11-02 18:45:49 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/sock0.sock --force test -e 'start slave'
2017-11-02 18:48:39 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/sock0.sock --force test -e 'show slave status\G'
2017-11-02 18:48:47 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/socket.sock --force test -e 'CREATE TABLE `dsns` (
                          `id` int(11) NOT NULL AUTO_INCREMENT,
                          `parent_id` int(11) DEFAULT NULL,
                          `dsn` varchar(255) NOT NULL,
                          PRIMARY KEY (`id`))
                        '
2017-11-02 18:48:53 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/sock0.sock --force test -e 'select @@port'
2017-11-02 18:48:58 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231017-percona-server-5.7.19-17-linux-x86_64-debug/socket.sock --force test -e 'insert into dsns(id, parent_id, dsn) values(22, 54, "h=127.0.0.1,u=root,P=53602")'
```

**Comment by ShahriyarR** [comment]
Failed with PS 5.7 test.

```
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.9', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/MySQL-AutoXtraBackup/autoxtrabackup.py", line 177, in all_procedure
    test_obj.wipe_backup_prepare_copyback(basedir=basedir)
  File "/home/shahriyar.rzaev/MySQL-AutoXtraBackup/prepare_env_test_mode/runner_test_mode.py", line 336, in wipe_backup_prepare_copyback
    file_name="cl_node{}".format(i)):
  File "/home/shahriyar.rzaev/MySQL-AutoXtraBackup/prepare_env_test_mode/runner_test_mode.py", line 227, in run_change_master
    self.run_sql_command(reset_master.format(mysql_slave_client_cmd))
  File "/home/shahriyar.rzaev/MySQL-AutoXtraBackup/prepare_env_test_mode/runner_test_mode.py", line 133, in run_sql_command
    raise RuntimeError("Failed to run SQL command -> {}".format(output))
RuntimeError: Failed to run SQL command -> ERROR 1049 (42000): Unknown database 'test'
2017-11-02 19:33:44 DEBUG    <pid.PidFile object at 0x7ff3b5ecf0e8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

**Comment by ShahriyarR** [comment]
So need to shutdown slave after each run.
