### ISSUE TITLE
AttributeError: 'GeneralClass' object has no attribute 'pid_dir'

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#16]
```
/opt/Python-3.3.2/bin/autoxtrabackup --backup
Traceback (most recent call last):
  File "/opt/Python-3.3.2/bin/autoxtrabackup", line 9, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.1', 'console_scripts', 'autoxtrabackup')()
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/click-6.7-py3.3.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/Python-3.3.2/lib/python3.3/site-packages/mysql_autoxtrabackup-1.4.1-py3.3.egg/autoxtrabackup.py", line 57, in all_procedure
AttributeError: 'GeneralClass' object has no attribute 'pid_dir'
```

**Comment by ShahriyarR** [comment]
seems to be version related.
With Python 3.5.3 there is no such issue.

**Comment by ShahriyarR** [comment]
Closing for now.
