### ISSUE TITLE
Require autoxtrabackup to be run under root or sudo

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#166]
I got the error with recent changes:

```
$ autoxtrabackup
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.9', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.9-py3.5.egg/autoxtrabackup.py", line 170, in all_procedure
  File "/home/shahriyar.rzaev/Python_interpreters/Python_3_5_3/lib/python3.5/logging/handlers.py", line 150, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/home/shahriyar.rzaev/Python_interpreters/Python_3_5_3/lib/python3.5/logging/handlers.py", line 57, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/home/shahriyar.rzaev/Python_interpreters/Python_3_5_3/lib/python3.5/logging/__init__.py", line 1009, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/shahriyar.rzaev/Python_interpreters/Python_3_5_3/lib/python3.5/logging/__init__.py", line 1038, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/var/log/autoxtrabackup.log'
```

So it should print the --help if no options passed.
The thing is autoxtrabackup should run with root or sudo, because it is using xtrabackup and doing some sort of directory works.

**Comment by ShahriyarR** [comment]
I have changed my mind on forcing global root/sudo usage, because it will break remote interpreter execution and some other scripts which is crucial for development process.
Rather, added inside code:

```
$ autoxtrabackup 
[Errno 13] Permission denied: '/var/log/autoxtrabackup.log' Please consider to run as root or sudo

$ autoxtrabackup --backup
[Errno 13] Permission denied: '/var/log/autoxtrabackup.log' Please consider to run as root or sudo
```

**Comment by ShahriyarR** [comment]
Can be merged now.
