### ISSUE TITLE
Add support for stream=tar for streaming

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#194]
For now the tool has only --stream=xbstream format.

**Comment by ShahriyarR** [comment]
```
2017-11-27 09:06:41 DEBUG    The following backup command will be executed /home/shahriyar.rzaev/XB_TEST/server_dir/target/percona-xtrabackup-2.4.x-debug/bin/xtrabackup --defaults-file= --user=root --password=''  --target-dir=/home/shahriyar.rzaev/XB_TEST/backup_dir/ps_5_7_x_2_4/full/2017-11-27_09-06-41 --backup --socket=/home/shahriyar.rzaev/XB_TEST/server_dir/PS231117-5.7.20-18-linux-x86_64-debug/socket.sock --compress=quicklz --compress-chunk-size=65536 --compress-threads=4 --encrypt=AES256 --encrypt-key=VVTBwgM4UhwkTTV98fhuj+D1zyWoA89K --encrypt-threads=4 --encrypt-chunk-size=65536 --slave-info --no-version-check --core-file --parallel=10 --throttle=40 --keyring-file-data=/home/shahriyar.rzaev/XB_TEST/server_dir/PS231117-5.7.20-18-linux-x86_64-debug/mysql-keyring/keyring --stream="tar" > /home/shahriyar.rzaev/XB_TEST/backup_dir/ps_5_7_x_2_4/full/2017-11-27_09-06-41/full_backup.tar
2017-11-27 09:06:41 DEBUG    Starting /home/shahriyar.rzaev/XB_TEST/server_dir/target/percona-xtrabackup-2.4.x-debug/bin/xtrabackup
2017-11-27 09:06:41 ERROR    FAILED: FULL BACKUP
2017-11-27 09:06:41 ERROR    171127 09:06:41 Connecting to MySQL server host: localhost, user: root, password: set, port: not set, socket: /home/shahriyar.rzaev/XB_TEST/server_dir/PS231117-5.7.20-18-linux-x86_64-debug/socket.sock
Using server version 5.7.20-18-debug
/home/shahriyar.rzaev/XB_TEST/server_dir/target/percona-xtrabackup-2.4.x-debug/bin/xtrabackup version 2.4.8 based on MySQL server 5.7.13 Linux (x86_64) (revision id: )
xtrabackup: error: compressed and encrypted backups are incompatible with the 
'tar' streaming format. Use --stream=xbstream instead.
2017-11-27 09:06:41 DEBUG    <pid.PidFile object at 0x7f97b577dcc8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.5.0', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.0-py3.5.egg/autoxtrabackup.py", line 239, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.0-py3.5.egg/master_backup_script/backuper.py", line 691, in all_backup
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.0-py3.5.egg/master_backup_script/backuper.py", line 343, in full_backup
RuntimeError: FAILED: FULL BACKUP
```

**Comment by ShahriyarR** [comment]
Due to error it is clear that compression + encryption backups is not supported by tar format.

**Comment by ShahriyarR** [comment]
So it turned out it is impossible to create incremental backups is tar streaming.
I need only configure to take full backup with --stream=tar
```
2017-11-27 10:27:29 DEBUG    The following backup command will be executed /home/shahriyar.rzaev/XB_TEST/server_dir/target/percona-xtrabackup-2.4.x-debug/bin/xtrabackup --defaults-file= --user=root --password='' --target-dir=/home/shahriyar.rzaev/XB_TEST/backup_dir/ps_5_7_x_2_4/inc/2017-11-27_10-27-29 --incremental-basedir=/home/shahriyar.rzaev/XB_TEST/backup_dir/ps_5_7_x_2_4/full/2017-11-27_10-27-07 --backup --socket=/home/shahriyar.rzaev/XB_TEST/server_dir/PS231117-5.7.20-18-linux-x86_64-debug/socket.sock --slave-info --no-version-check --core-file --parallel=10 --throttle=40 --keyring-file-data=/home/shahriyar.rzaev/XB_TEST/server_dir/PS231117-5.7.20-18-linux-x86_64-debug/mysql-keyring/keyring --stream="tar" > /home/shahriyar.rzaev/XB_TEST/backup_dir/ps_5_7_x_2_4/inc/2017-11-27_10-27-29/inc_backup.tar
2017-11-27 10:27:29 ERROR    FAILED: INCREMENTAL BACKUP
2017-11-27 10:27:29 ERROR    171127 10:27:29 Connecting to MySQL server host: localhost, user: root, password: set, port: not set, socket: /home/shahriyar.rzaev/XB_TEST/server_dir/PS231117-5.7.20-18-linux-x86_64-debug/socket.sock
Using server version 5.7.20-18-debug
/home/shahriyar.rzaev/XB_TEST/server_dir/target/percona-xtrabackup-2.4.x-debug/bin/xtrabackup version 2.4.8 based on MySQL server 5.7.13 Linux (x86_64) (revision id: )
incremental backup from 2573994 is enabled.
xtrabackup: error: streaming incremental backups are incompatible with the 
'tar' streaming format. Use --stream=xbstream instead.
```

**Comment by ShahriyarR** [comment]
During tests, could not find any other issues.
So can be merged to release_v1.5.1
