### ISSUE TITLE
Add support for PS 5.5 for --test_mode

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#197]
* Make it possible to build -> OK
* Generate config for PS 5.5 -> OK
* Run it with --test_mode

**Comment by ShahriyarR** [comment]
```
2017-11-23 16:53:57 DEBUG    Running -> /home/shahriyar.rzaev/XB_TEST/server_dir/PS231117-5.5.58-38.10-linux-x86_64-debug/bin/mysql -A -uroot -S/home/shahriyar.rzaev/XB_TEST/server_dir/PS231117-5.5.58-38.10-linux-x86_64-debug/sock1.sock --force test -e 'reset master'
2017-11-23 16:53:57 DEBUG    <pid.PidFile object at 0x7f986fb22cc8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.5.0', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.0-py3.5.egg/autoxtrabackup.py", line 209, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.0-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 426, in wipe_backup_prepare_copyback
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.0-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 325, in run_change_master
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.0-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 282, in get_gtid_address
IndexError: list index out of range
```

**Comment by ShahriyarR** [comment]
The reason of the fail above is:

```
        if is_slave is None:
            # Run SET GLOBAL gtid_purged, get from master's xtrabackup_binlog_info
            gtid_pos = self.get_gtid_address(full_backup_dir=full_backup_dir)
            gtid_purged = '{} -e \'set global gtid_purged=\"{}\"\''.format(mysql_slave_client_cmd, gtid_pos)
            self.run_sql_command(gtid_purged)
        else:
            # Run SET GLOBAL gtid_purged, get from slave's xtrabackup_slave_info
            sql_cmd = self.get_gtid_xtrabackup_slave_info(full_backup_dir=full_backup_dir)
            gtid_purged = '{} -e \"{}\"'.format(mysql_slave_client_cmd, sql_cmd)
            self.run_sql_command(gtid_purged)
```

It is going to parse xtrabackup_binlog_info file, which is different in PS 5.5, i.e there is no GTID thing with this version of PS:

```
$ cat xtrabackup_binlog_info 
mysql-bin.000005	9743345
```
Due to this I need to add check if the '5.5' in basedir, then do not parse those file or parse with different way.

**Comment by ShahriyarR** [comment]
The change master command should be changed as well:

```
mysql> CHANGE MASTER TO
    ->     MASTER_HOST='master_host_name',
    ->     MASTER_USER='replication_user_name',
    ->     MASTER_PASSWORD='replication_password',
    ->     MASTER_LOG_FILE='recorded_log_file_name',
    ->     MASTER_LOG_POS=recorded_log_position;
```

**Comment by ShahriyarR** [comment]
Done and merged to release_v1.5.1
