### ISSUE TITLE
autoxtrabackup --partial traceback error

### ISSUE THREAD

**Issue by knulphaller** [ShahriyarR/MySQL-AutoXtraBackup#2]
when mysql not installed or down, autoxtrabackup --partial gives traceback error:

    lpiexam@lpiexam-VirtualBox:/$ autoxtrabackup --partial
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/mysql_connector_python-2.0.3-                       py3.4.egg/mysql/connector/network.py", line 469, in open_connection
    ConnectionRefusedError: [Errno 111] Connection refused

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/bin/autoxtrabackup", line 9, in <module>
        load_entry_point('mysql-autoxtrabackup==1.0', 'console_scripts', 'autoxtrabackup')()
      File "/usr/local/lib/python3.4/dist-packages/click-4.0-py3.4.egg/click/core.py", line 664, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/click-4.0-py3.4.egg/click/core.py", line 644, in main
        rv = self.invoke(ctx)
      File "/usr/local/lib/python3.4/dist-packages/click-4.0-py3.4.egg/click/core.py", line 837, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.4/dist-packages/click-4.0-py3.4.egg/click/core.py", line 464, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/mysql_autoxtrabackup-1.0-    py3.4.egg/autoxtrabackup.py", line 38, in all_procedure
      File "/usr/local/lib/python3.4/dist-packages/mysql_autoxtrabackup-1.0-py3.4.egg/partial_recovery/partial.py", line 32, in __init__
      File "/usr/local/lib/python3.4/dist-packages/mysql_connector_python-2.0.3-py3.4.egg/mysql/connector/__init__.py", line 162, in connect
      File "/usr/local/lib/python3.4/dist-packages/mysql_connector_python-2.0.3-py3.4.egg/mysql/connector/connection.py", line 129, in __init__
      File "/usr/local/lib/python3.4/dist-packages/mysql_connector_python-2.0.3-py3.4.egg/mysql/connector/connection.py", line 454, in connect
      File "/usr/local/lib/pyt6hon3.4/dist-packages/mysql_connector_python-2.0.3-py3.4.egg/mysql/connector/connection.py", line 417, in _open_connection
      File "/usr/local/lib/python3.4/dist-packages/mysql_connector_python-2.0.3-    py3.4.egg/mysql/connector/network.py", line 472, in open_connection
    mysql.connector.errors.InterfaceError: 2003: Can't connect to MySQL server on 'localhost:3306'     (111 Connection refused)
    Exception ignored in: <bound method PartialRecovery.__del__ of     <partial_recovery.partial.PartialRecovery object at 0x7f711aaae2b0>>
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/mysql_autoxtrabackup-1.0-    py3.4.egg/partial_recovery/partial.py", line 37, in __del__
    AttributeError: 'PartialRecovery' object has no attribute 'cnx'

**Comment by ShahriyarR** [comment]
Thank you for report.
For using --partial recovery option, MySQL server must be running.
i will fix it and add informative error message indicating this condition.

**Comment by ShahriyarR** [comment]
Fixed as:
Added connection try:except for connection state checking.
