### ISSUE TITLE
Make possible to build xtrabackups in --test_mode prepare env process

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#209]
For now I am getting the xtrabackup binaries from jenkins job.
To be much more convenient, the tool should build them locally with --test_mode environment prepare stage

**Comment by ShahriyarR** [comment]
The result of tests:

```
$ bats prepare_env.bats
 ✓ Running test_clone_percona_qa
 ✓ Running test_clone_ps_server_from_conf
 ✓ Running test_clone_pxb
 ✓ Running test_build_pxb
 ✓ Running test_build_server
 ✓ Running test_prepare_startup
 ✓ Running test_start_server
 ✓ Running test_extract_xb_archive
 ✓ Running test_generate_config_files
```

Can be merged to release_v1.5.1

**Comment by ShahriyarR** [comment]
Not yet:

```
$ autoxtrabackup -v -lf /home/shahriyar.rzaev/XB_TEST/autoxtrabackup_2_4_5_7.log -l DEBUG --defaults_file=/home/shahriyar.rzaev/XB_TEST/server_dir/xb_2_4_ps_5_7.conf --test_mode
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.5.0', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.0-py3.5.egg/autoxtrabackup.py", line 179, in all_procedure
    config = GeneralClass(defaults_file)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.0-py3.5.egg/general_conf/generalops.py", line 128, in __init__
    self.pxb_branches = TEST['pxb_branches']
  File "/home/shahriyar.rzaev/Python_interpreters/Python_3_5_3/lib/python3.5/configparser.py", line 1230, in __getitem__
    raise KeyError(key)
KeyError: 'pxb_branches'
```

**Comment by ShahriyarR** [comment]
Fixed.
