### ISSUE TITLE
ERROR    /bin/sh: /home/shahriyar.rzaev/XB_TEST/server_dir/PS291117-percona-server-5.7.20-18-linux-x86_64-debug/start_dynamic: No such file or directory

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#213]
```
2017-11-29 11:30:07 ERROR    Error occurred while starting MySQL!
2017-11-29 11:30:07 ERROR    /bin/sh: /home/shahriyar.rzaev/XB_TEST/server_dir/PS291117-percona-server-5.7.20-18-linux-x86_64-debug/start_dynamic: No such file or directory
2017-11-29 11:30:07 DEBUG    <pid.PidFile object at 0x7ff4d5d1b368> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.5.0', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.0-py3.5.egg/autoxtrabackup.py", line 203, in all_procedure
    test_obj.wipe_backup_prepare_copyback(basedir=basedir)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.0-py3.5.egg/prepare_env_test_mode/runner_test_mode.py", line 452, in wipe_backup_prepare_copyback
    options=slave_full_options)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.0-py3.5.egg/backup_prepare/prepare.py", line 1001, in start_mysql_func
    raise RuntimeError("Error occurred while starting MySQL!")
RuntimeError: Error occurred while starting MySQL!
```

**Comment by ShahriyarR** [comment]
Seems to be fixed.
