### ISSUE TITLE
Failed with --defaults-file option; should add check for config file prior passing to parser

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#26]
The result of run:

```
sh@sh-ubuntu:~$ /home/sh/REPOS/python3_5_3/bin/autoxtrabackup --defaults_file=fgdjgdfg --backup
Traceback (most recent call last):
  File "/home/sh/REPOS/python3_5_3/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.4', 'console_scripts', 'autoxtrabackup')()
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.4-py3.5.egg/autoxtrabackup.py", line 70, in all_procedure
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.4-py3.5.egg/master_backup_script/backuper.py", line 474, in all_backup
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.4-py3.5.egg/general_conf/check_env.py", line 386, in check_all_env
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.4-py3.5.egg/general_conf/check_env.py", line 23, in check_mysql_uptime
AttributeError: 'CheckEnv' object has no attribute 'mysqladmin'
```

**Comment by bfarayev** [comment]
can you confirm if this error occurs when the specified file doesn't exist or the given path isn't valid?

**Comment by ShahriyarR** [comment]
Fixed.
