### ISSUE TITLE
Handle the KeyErrors if the specified config file is not valid: KeyError: 'MySQL'

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#27]
The result:

```
sudo /home/sh/REPOS/python3_5_3/bin/autoxtrabackup --defaults_file=/tmp/fff.cnf --backup -v -l DEBUG
<pid.PidFile object at 0x7f3e6acda868> entering setup
<pid.PidFile object at 0x7f3e6acda868> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7f3e6acda868> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7f3e6acda868> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/sh/REPOS/python3_5_3/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.4', 'console_scripts', 'autoxtrabackup')()
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.4-py3.5.egg/autoxtrabackup.py", line 76, in all_procedure
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.4-py3.5.egg/master_backup_script/backuper.py", line 35, in __init__
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.4-py3.5.egg/general_conf/generalops.py", line 19, in __init__
  File "/usr/lib/python3.5/configparser.py", line 956, in __getitem__
    raise KeyError(key)
KeyError: 'MySQL'
<pid.PidFile object at 0x7f3e6acda868> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

**Comment by ShahriyarR** [comment]
This error is encountered if the file is totally empty.

**Comment by ShahriyarR** [comment]
Or the config file has sections but wrong options:
```
/home/sh/REPOS/python3_5_3/bin/autoxtrabackup --backup --defaults_file=/home/sh/txt.ff -v -l DEBUG
<pid.PidFile object at 0x7f82636b4868> entering setup
<pid.PidFile object at 0x7f82636b4868> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7f82636b4868> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7f82636b4868> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/sh/REPOS/python3_5_3/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.4', 'console_scripts', 'autoxtrabackup')()
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.4-py3.5.egg/autoxtrabackup.py", line 76, in all_procedure
    b = Backup(config=defaults_file)
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.4-py3.5.egg/master_backup_script/backuper.py", line 35, in __init__
  File "/home/sh/REPOS/python3_5_3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.4-py3.5.egg/general_conf/generalops.py", line 20, in __init__
  File "/usr/lib/python3.5/configparser.py", line 1230, in __getitem__
    raise KeyError(key)
KeyError: 'mysql'
<pid.PidFile object at 0x7f82636b4868> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

**Comment by bfarayev** [comment]
That's right. 
Validation rules on file:
- File should exists
- It should be a valid configuration file i.e. it should contain [MySQL], [Backup], [Compress],[Encrypt] and [Commands] headers as far as I tested.

**Comment by ShahriyarR** [comment]
@bfarayev 
I am curious about did you check the following scenario?
For eg, The config file has valid structure as you described but have wrong options below headers.
How it will act?

**Comment by bfarayev** [comment]
I checked it with this file: 
```
[MySQL]
[Backup]
[Compress]
[Encrypt]
[Commands]
```
So based on file validation, it's correct but some fields are missing. First we need to identify which fields are mandatory and make sure they exist in file content.

So the test result is: 
```
File is valid.
<pid.PidFile object at 0x105d93ea8> entering setup
<pid.PidFile object at 0x105d93ea8> create pidfile: /tmp/autoxtrabackup.py.pid
<pid.PidFile object at 0x105d93ea8> check pidfile: /tmp/autoxtrabackup.py.pid
<pid.PidFile object at 0x105d93ea8> closing pidfile: /tmp/autoxtrabackup.py.pid
Traceback (most recent call last):
  File "autoxtrabackup.py", line 135, in <module>
    all_procedure()
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "autoxtrabackup.py", line 106, in all_procedure
    b = Backup(config=defaults_file)
  File "/Users/bahtiyar/Desktop/MySQL-AutoXtraBackup/master_backup_script/backuper.py", line 35, in __init__
    GeneralClass.__init__(self, self.conf)
  File "/Users/bahtiyar/Desktop/MySQL-AutoXtraBackup/general_conf/generalops.py", line 20, in __init__
    self.mysql = DB['mysql']
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/configparser.py", line 1230, in __getitem__
    raise KeyError(key)
KeyError: 'mysql'
<pid.PidFile object at 0x105d93ea8> closing pidfile: /tmp/autoxtrabackup.py.pid
```

Note the lowercase `mysql`. it's the missing key, rather than header `[MySQL]`.

**Comment by bfarayev** [comment]
So the minimal file structure should look like this. However, I'm thinking if it's worth checking these fields while validation? 

```
 [MySQL]
 mysql=
 mycnf=
 mysqladmin=
 mysql_user=
 mysql_password=
 datadir=
 tmpdir=
 tmp=

 [Backup]
 backupdir=
 backup_tool=
 xtra_prepare=

 [Compress]

 [Encrypt]

 [Commands]
 start_mysql_command=
 NORMAL   bck1.conf          3%     1:7
 1 bck1.conf                                                                                X
 datadir=
 tmpdir=
 tmp=

 [Backup]
 backupdir=
 backup_tool=
 xtra_prepare=

 [Compress]

 [Encrypt]

 [Commands]
 start_mysql_command=
 stop_mysql_command=
 systemd_start_mysql=
 systemd_stop_mysql=
 chown_command=
 systemd_start_mariadb=
 systemd_stop_mariadb=
```

**Comment by ShahriyarR** [comment]
Exactly,
The mandatory options are there.
After this will be implemented, one will easily expand further.

**Comment by ShahriyarR** [comment]
Fixed.
