### ISSUE TITLE
RuntimeError: FAILED: Table is not recovered is faild

### ISSUE THREAD

**Issue by weiyanwei412** [ShahriyarR/MySQL-AutoXtraBackup#280]
mysql  Server version: 5.7.21-log 
innobackupex version 2.4.6 Linux (x86_64) (revision id: 54967d1)

root@<node1||/opt/auto-xtrabackup/MySQL-AutoXtraBackup>:#/opt/Python-3.5.3/bin/python3 autoxtrabackup.py -v -lf /data/xtrabackup/autoxtrabackup.log -l DEBUG --defaults_file=/etc/bck.conf --partial
2018-05-21 13:35:18 DEBUG    <pid.PidFile object at 0x2b62617f24a8> entering setup
2018-05-21 13:35:18 DEBUG    <pid.PidFile object at 0x2b62617f24a8> create pidfile: /tmp/autoxtrabackup.py.pid
2018-05-21 13:35:18 DEBUG    <pid.PidFile object at 0x2b62617f24a8> check pidfile: /tmp/autoxtrabackup.py.pid
Type Database name: zx_election
Type Table name: vote_info
2018-05-21 13:35:45 DEBUG    Running mysqladmin command -> /usr/local/mysql/bin/mysqladmin --defaults-file=/etc/my.cnf --user=root --password=**** status --host=127.0.0.1 --port=3306
2018-05-21 13:35:45 DEBUG    OK: Server is Up and running
2018-05-21 13:35:45 DEBUG    Checking if innodb_file_per_table is enabled
2018-05-21 13:35:46 ERROR    FAILED: InnoDB file per-table Check
2018-05-21 13:35:46 ERROR    mysql: [Warning] Using a password on the command line interface can be insecure.
@**mysql: [ERROR] Unknown suffix '.' used for variable 'port' (value '127.0.0.1')
mysql: [ERROR] /usr/local/mysql/bin/mysql: Error while setting value '127.0.0.1' to 'port'
2018-05-21 13:35:46 ERROR    FAILED: Table is not recovered**
2018-05-21 13:35:46 ERROR    FAILED: InnoDB file per-table Check
2018-05-21 13:35:46 DEBUG    <pid.PidFile object at 0x2b62617f24a8> closing pidfile: /tmp/autoxtrabackup.py.pid
Traceback (most recent call last):
  File "/opt/auto-xtrabackup/MySQL-AutoXtraBackup/partial_recovery/partial.py", line 359, in final_actions
    self.check_innodb_file_per_table()
  File "/opt/auto-xtrabackup/MySQL-AutoXtraBackup/partial_recovery/partial.py", line 71, in check_innodb_file_per_table
    raise RuntimeError("FAILED: InnoDB file per-table Check")
RuntimeError: FAILED: InnoDB file per-table Check

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "autoxtrabackup.py", line 306, in <module>
    all_procedure()
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "autoxtrabackup.py", line 276, in all_procedure
    c.final_actions()
  File "/opt/auto-xtrabackup/MySQL-AutoXtraBackup/partial_recovery/partial.py", line 376, in final_actions
    raise RuntimeError("FAILED: Table is not recovered")
RuntimeError: FAILED: Table is not recovered

**Comment by ShahriyarR** [comment]
Hi and thanks for report.
It seems to be mysql connection issue here:
`/usr/local/mysql/bin/mysql: Error while setting value '127.0.0.1' to 'port'`

Could you check if something wrong with config?

**Comment by weiyanwei412** [comment]
Thank you for your response!
This partial.py script maybe  problematic！ 
  if  true   but    else  running!
 else:
            logger.error("FAILED: InnoDB file per-table Check")
            logger.error(output)
            raise RuntimeError("FAILED: InnoDB file per-table Check")

**Comment by ShahriyarR** [comment]
@weiyanwei412 please submit a pull request if you have code suggestions, improvements.
All kinds of help are appreciated.

**Comment by ShahriyarR** [comment]
Closing as there is no activity here.
