### ISSUE TITLE
No /etc/bck.conf?

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#295]
I have no bck.conf after installing with pip3

I also get this error when running autoxtrabackup (but maybe because no conf?):

```
Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 11, in <module>
    sys.exit(all_procedure())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autoxtrabackup.py", line 200, in all_procedure
    validate_file(defaults_file)
  File "/usr/local/lib/python3.6/dist-packages/autoxtrabackup.py", line 105, in validate_file
    raise FileNotFoundError("Specified file does not exist.")
FileNotFoundError: Specified file does not exist.

```

**Comment by ShahriyarR** [comment]
Hi, thanks for report.
Now checking.

**Comment by BarbzYHOOL** [comment]
I added the conf manually and it worked but I had to copy everything by hand, was annoying :P

**Comment by ShahriyarR** [comment]
Yes that is annoying.
I should check if something was broken in package.
Because as I noticed installing from source works good.

**Comment by ShahriyarR** [comment]
There is no such config file anymore.
Please test it with new `1.5.3` version of `autoxtrabackup`.
Closing for now.

**Comment by BarbzYHOOL** [comment]
Ah ok lol hopefully I looked at this because I have everything set up for 1.5.2... :'( poor me
