### ISSUE TITLE
Failed to install release_v1.5.3 branch on vagrant

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#308]
It is failing as:
```
$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from general_conf import path_config
  File "/vagrant/general_conf/__init__.py", line 1, in <module>
    from general_conf import generalops
  File "/vagrant/general_conf/generalops.py", line 3, in <module>
    import humanfriendly
ImportError: No module named 'humanfriendly'
```

Seems to be the reason is in `setup.py`:
```
from general_conf import path_config

datafiles = [(path_config.config_path, ['general_conf/autoxtrabackup.cnf'])]
```

**Comment by ShahriyarR** [comment]
No it was related `__init__.py` inside `general_conf`.
Fixed by removing explicit imports from `__init__.py`
