### ISSUE TITLE
I upgraded autoxtrabackup but no config file

### ISSUE THREAD

**Issue by BarbzYHOOL** [ShahriyarR/MySQL-AutoXtraBackup#332]
I updated as root, and then I check /root/.autoxtrabackup and it doesn't exist

@ShahriyarR

**Comment by BarbzYHOOL** [comment]
Also when I run it:
runuser -s "/bin/sh"  mysql -c "autoxtrabackup --backup -v -l DEBUG" 
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/mysql/.autoxtrabackup/autoxtrabackup.log'

---
Ah okay I need to change default log location :(

**Comment by BarbzYHOOL** [comment]
So if i set another logfile or run it as root:

```
Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 11, in <module>
    sys.exit(all_procedure())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autoxtrabackup.py", line 202, in all_procedure
    validate_file(defaults_file)
  File "/usr/local/lib/python3.6/dist-packages/autoxtrabackup.py", line 107, in validate_file
    raise FileNotFoundError("Specified file does not exist.")
FileNotFoundError: Specified file does not exist.

```

**Comment by BarbzYHOOL** [comment]
Alright needed to set the --defaults_file option (this is an horrible name xD, it should be "--config" and "-c")

```
2018-12-26 17:54:08 DEBUG    <pid.PidFile object at 0x7fb138eca908> closing pidfile: /tmp/autoxtrabackup/pid/autoxtrabackup.pid
Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 11, in <module>
    sys.exit(all_procedure())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/autoxtrabackup.py", line 266, in all_procedure
    b.all_backup()
  File "/usr/local/lib/python3.6/dist-packages/master_backup_script/backuper.py", line 917, in all_backup
    self.inc_backup()
  File "/usr/local/lib/python3.6/dist-packages/master_backup_script/backuper.py", line 815, in inc_backup
    logger.debug("The following backup command will be executed {}".format(filteredargs))
UnboundLocalError: local variable 'filteredargs' referenced before assignment
2018-12-26 17:54:08 DEBUG    <pid.PidFile object at 0x7fb138eca908> closing pidfile: /tmp/autoxtrabackup/pid/autoxtrabackup.pid

```

**Comment by ShahriyarR** [comment]
The last one is already known issue :)
It is fixed but not released yet, will be released as part of 1.5.4

**Comment by ShahriyarR** [comment]
@BarbzYHOOL I will kindly ask you to test 1.5.4 version as i am going to improve some vital things.
So if you have time checkout please release_v1.5.4 branch and do your best to break it)

**Comment by BarbzYHOOL** [comment]
"So if you have time checkout please release_v1.5.4 branch and do your best to break it)"

Ok lol i'm gonna try

**Comment by BarbzYHOOL** [comment]
@ShahriyarR 
Collecting mysql-autoxtrabackup==
  Could not find a version that satisfies the requirement mysql-autoxtrabackup== (from versions: 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.5.0, 1.5.1, 1.5.2, 1.5.3)
No matching distribution found for mysql-autoxtrabackup==

no 1.5.4

ah yes i use pip3 to install actually, not git

**Comment by ShahriyarR** [comment]
:) Yes you need to clone repo, then checkout to release_v1.5.4 branch and then setup using setup.py install.

**Comment by BarbzYHOOL** [comment]
Installed with `pip3 install git+https://github.com/ShahriyarR/MySQL-AutoXtraBackup@release_v1.5.4` but it says `Successfully installed mysql-autoxtrabackup-1.5.3`
However here you didn't update the magic number https://github.com/ShahriyarR/MySQL-AutoXtraBackup/blob/release_v1.5.4/setup.py so i guess it's fine  (please don't forget small things like that :D)


I tried the same commands and it works now. However I have some small suggestions to make the usage more practical/consistent

**Comment by ShahriyarR** [comment]
:)) I did not forget. In general the version bump will be happen at the end of all feature implementations and fixes. When the release process ends, it will be merged to master branch with updated version number.
The strategy I am using here is simple:
* Opening new release branch from fresh master.
* Fix all bugs, implement features inside separate issue branches named as -> `bugfix_issue[num]`.
* PR to this new release branch and merge it.
* Then create PR from this release branch to master branch and update further.
* At the end do last checks, run tests and change version number and merge it to master branch.
* Create distribution packages and upload them to PyPi

**Comment by BarbzYHOOL** [comment]
i think you should bump version number as soon as you create the branch but it's minor :D
