### ISSUE TITLE
mysql: [ERROR] Unknown suffix '.' used for variable 'port' (value '127.0.0.1')

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#353]
Failed partial recovery:

```
$ sudo /home/shako/REPOS/MySQL-AutoXtraBackup/.venv/bin/autoxtrabackup -v -l DEBUG --partial
2019-01-20 14:13:52 DEBUG    [__init__.py:71] <pid.PidFile object at 0x7f3543e8e868> entering setup
2019-01-20 14:13:52 DEBUG    [__init__.py:161] <pid.PidFile object at 0x7f3543e8e868> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2019-01-20 14:13:52 DEBUG    [__init__.py:148] <pid.PidFile object at 0x7f3543e8e868> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Type Database name: test
Type Table name: t1
2019-01-20 14:13:55 DEBUG    [check_env.py:49] Running mysqladmin command -> /usr/bin/mysqladmin --defaults-file= --user=root --password='*' status --host=127.0.0.1 --port=3306
2019-01-20 14:13:55 DEBUG    [check_env.py:54] OK: Server is Up and running
2019-01-20 14:13:55 DEBUG    [partial.py:59] Checking if innodb_file_per_table is enabled
2019-01-20 14:13:55 ERROR    [partial.py:69] FAILED: InnoDB file per-table Check
2019-01-20 14:13:55 ERROR    [partial.py:70] mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [ERROR] Unknown suffix '.' used for variable 'port' (value '127.0.0.1')
mysql: [ERROR] /usr/bin/mysql: Error while setting value '127.0.0.1' to 'port'
2019-01-20 14:13:55 ERROR    [partial.py:374] FAILED: Table is not recovered
2019-01-20 14:13:55 ERROR    [partial.py:375] FAILED: InnoDB file per-table Check
2019-01-20 14:13:55 DEBUG    [__init__.py:188] <pid.PidFile object at 0x7f3543e8e868> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shako/REPOS/MySQL-AutoXtraBackup/.venv/lib/python3.6/site-packages/mysql_autoxtrabackup-1.5.5-py3.6.egg/partial_recovery/partial.py", line 359, in final_actions
    self.check_innodb_file_per_table()
  File "/home/shako/REPOS/MySQL-AutoXtraBackup/.venv/lib/python3.6/site-packages/mysql_autoxtrabackup-1.5.5-py3.6.egg/partial_recovery/partial.py", line 71, in check_innodb_file_per_table
    raise RuntimeError("FAILED: InnoDB file per-table Check")
RuntimeError: FAILED: InnoDB file per-table Check
```

**Comment by BarbzYHOOL** [comment]
when does it happen?

**Comment by ShahriyarR** [comment]
It happens while doing partial recovery. See the command.
Maybe it is issue of formatting will see.

**Comment by BarbzYHOOL** [comment]
or a new type of port xD
