### ISSUE TITLE
TypeError: all_procedure() got an unexpected keyword argument 'log_level'

### ISSUE THREAD

**Issue by pbowyer** [ShahriyarR/MySQL-AutoXtraBackup#369]
I installed from source today on an Ubuntu 18.04 server. Using the automatically generated config file, `autoxtrabackup --help` works but `autoxtrabackup --backup` fails with:
```
# autoxtrabackup --backup
Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.5.4', 'console_scripts', 'autoxtrabackup')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: all_procedure() got an unexpected keyword argument 'log_level'
```

I am not a Python programmer (sorry) so am stuck with what's causing this error?

**Comment by BarbzYHOOL** [comment]
maybe remove 'log_level' from your config and try again (sorry can't help more)

**Comment by Pahanda** [comment]
I'm also running into this problem, also in Ubuntu 18.04 LTS.

I'm not able to install via pip:
```
Collecting mysql-autoxtrabackup
  Using cached https://files.pythonhosted.org/packages/ff/43/cc91dfc18c4dd1eecc8ad673377291b22c178482db9197b3b25007a9560b/mysql_autoxtrabackup-1.5.4-py3-none-any.whl
Requirement already satisfied: click>=3.3 in /usr/lib/python3/dist-packages (from mysql-autoxtrabackup)
Requirement already satisfied: pytest in /usr/local/lib/python3.6/dist-packages/pytest-5.3.5-py3.6.egg (from mysql-autoxtrabackup)
Requirement already satisfied: pid>=2.0 in /usr/local/lib/python3.6/dist-packages/pid-2.2.5-py3.6.egg (from mysql-autoxtrabackup)
Collecting mysql-connector==2.1.4 (from mysql-autoxtrabackup)
  Could not find a version that satisfies the requirement mysql-connector==2.1.4 (from mysql-autoxtrabackup) (from versions: 2.1.7, 2.2.9)
No matching distribution found for mysql-connector==2.1.4 (from mysql-autoxtrabackup)

```
(looks like the version requirement for mysql-connector needs to be incremented)

And when I try to build from source, I get the error in the original post.  I'm on Python 3.6.8.

**Comment by BarbzYHOOL** [comment]
last time i spoke to shahriyarr, he said mysql-connector wasn't needed anymore, check master code or one of the latest PRs' comments

**Comment by ShahriyarR** [comment]
Yes, guys with the latest release there is no need for mysql-connector dependency package.
Also, I am going to make this tool more covered with tests and error handling will be improved in the upcoming version 2.0.
Closing now.
