### ISSUE TITLE
backup got failed 

### ISSUE THREAD

**Issue by bimith** [ShahriyarR/MySQL-AutoXtraBackup#370]
1, i have installed already mysql-autoxtrabackup using below command
pip3 install mysql-autoxtrabackup

after this one need to follow 

cd /home git clone https://github.com/ShahriyarR/MySQL-AutoXtraBackup.git
cd /home/MySQL-AutoXtraBackup/
python3 setup.py install      ---this command also?

2,when am trying to install with below command 
autoxtrabackup -v -lf /home/MySQL-Autoxtrabackup_2_4_5_7.log \
-l DEBUG --defaults_file=/home/XB_TEST/server_dir/xb_2_4_ps_5_7.conf --backup

am getting the error

pkg_resources.DistributionNotFound: The 'mysql-connector==2.1.4' distribution was not found and is required by mysql-autoxtrabackup

as per your instruction i have changed the link in setup.py
but now these error is showing

**Comment by ShahriyarR** [comment]
As far as I remember @BarbzYHOOL used to fix this issue somehow.
Could you please assist on this?

**Comment by BarbzYHOOL** [comment]
https://github.com/ShahriyarR/MySQL-AutoXtraBackup/issues/368 and in my fork the fix is there (on master or another branch)

**Comment by ShahriyarR** [comment]
Okay I will release the new version, with a bunch of stacked fixes.
It seems to be this project is still alive :)

**Comment by bimith** [comment]
thanks for respond

**Comment by bimith** [comment]
autoxtrabackup --backup -v -l DEBUG -lf /home/XB_TEST/backup_dir/xb.log --defaults-file=/home/XB_TEST/server_dir/bck.conf
Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.5.4', 'console_scripts', 'autoxtrabackup')()
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.4-py3.5.egg/autoxtrabackup.py", line 185, in all_procedure
    config = GeneralClass(defaults_file)
  File "/usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.4-py3.5.egg/general_conf/generalops.py", line 15, in __init__
    con.read(config)
  File "/usr/local/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/local/lib/python3.5/configparser.py", line 1077, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/home/XB_TEST/server_dir/bck.conf', line: 1
#'mysqladmin=/usr/bin/mysqladmin\n'--- What is this error here please advise me

**Comment by gitmstoute** [comment]
Hey @bimith, 
`configparser.MissingSectionHeaderError: File contains no section headers.`
I believe you're missing a `[mysqlbackup]` line ahead of the configs pertaining to mysqlbackup, in the file `/home/XB_TEST/server_dir/bck.conf`.

If that doesn't fix it please post the contents of the file.

**Comment by gitmstoute** [comment]
@bimith sorry the section would be like `[Backup]` rather than mysqlback. And it might not necessarily be that section, but it's complaining that the sections in general are missing.
