### ISSUE TITLE
Not an issue one doubt 

### ISSUE THREAD

**Issue by bimith** [ShahriyarR/MySQL-AutoXtraBackup#374]
Hi Dude,
once the full backup is completed next what time and all executing that will be cover only for incremental backups. and one more thing. if the database there is no changes another 2 hours 
what will happen, the full backup only will happen ?

**Comment by BarbzYHOOL** [comment]
>once the full backup is completed next what time and all executing that will be cover only for incremental backups

??? not understandable

> if the database there is no changes another 2 hours
what will happen, the full backup only will happen ?

not sure, good question

**Comment by gitmstoute** [comment]
> if the database there is no changes another 2 hours what will happen, the full backup only will happen ?
I believe xtrabackup will make an incremental backup, which just contains no updates. The full backup should only happen according to the schedule; if there are no changes, it won't cause another full backup.

**Comment by bimith** [comment]
autoxtrabackup --backup -v -l DEBUG -lf /else/xb_test/backup_dir/xb.log --defaults-file=/else/xb_test/server_dir/bck.cnf
Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.5.4', 'console_scripts', 'autoxtrabackup')()
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.4-py3.5.egg/autoxtrabackup.py", line 185, in all_procedure
    config = GeneralClass(defaults_file)
  File "/usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.4-py3.5.egg/general_conf/generalops.py", line 15, in __init__
    con.read(config)
  File "/usr/local/lib/python3.5/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/local/lib/python3.5/configparser.py", line 1089, in _read
    fpname, lineno)
configparser.DuplicateOptionError: While reading from '/else/xb_test/server_dir/bck.cnf' [line 36]: option 'xtra_options' in section 'Backup' already exists

i have cleared my backup directory but it is saying already backup is exist. How?

**Comment by bimith** [comment]
please suggest me to debug this issue

**Comment by gitmstoute** [comment]
@bimith the error message explains the issue, please read them carefully...

> configparser.DuplicateOptionError: While reading from '/else/xb_test/server_dir/bck.cnf' [line 36]: option 'xtra_options' in section 'Backup' already exists

In you file `/else/xb_test/server_dir/bck.cnf`, you have defined `xtra_options` in the `Backup` section more than once.

**Comment by bimith** [comment]
Now am facing only one issue we have two commands for restore one it is database full restore
under this only we have three option like prepare and prepare backups and restore immediately
and copy back immediately.

1. my question is whenever we are restoring the backups are full or partial we need to stop mysql service.
still i unable to restore partially and full
2. suppose i have taken on sunday full backup then on monday incremental backup 
next day i have given prepare command the another day incremental backup will work or not.

Kindly help me
