### ISSUE TITLE
/bin/sh: /usr/bin/mysqladmin: No such file or directory; seems to be the config file was parsed incorrectly

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#38]
Result:

```
[shahriyar.rzaev@qaserver-04 ~]$ autoxtrabackup --backup -v -l DEBUG --defaults_file=/home/shahriyar.rzaev/AutoXtrabackup_Configs/ps_5.7_master_bck.conf 
<pid.PidFile object at 0x7fc7247864a8> entering setup
<pid.PidFile object at 0x7fc7247864a8> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7fc7247864a8> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
/usr/bin/mysql exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-OK
/usr/bin/mysqladmin exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
MySQL configuration file exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+OK
Xtrabackup/Innobackupex exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-OK
Main backup directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-OK
Full Backup directory exists.+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+OK
Increment directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
Check status: STATUS+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-+-+-OK
################################################################
You have a full backup that is less than 86400 seconds old. - -#
We will take an incremental one based on recent Full Backup - -#
################################################################
mysqladmin ver command Failed
/bin/sh: /usr/bin/mysqladmin: No such file or directory
<pid.PidFile object at 0x7fc7247864a8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.5', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/autoxtrabackup.py", line 160, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/master_backup_script/backuper.py", line 593, in all_backup
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/master_backup_script/backuper.py", line 336, in inc_backup
UnboundLocalError: local variable 'args' referenced before assignment
<pid.PidFile object at 0x7fc7247864a8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

**Comment by clavezzo** [comment]
Hello. I installed the last version of autoxtrabackup, following the document, MySQL AutoXtrabackup
Documentation
Release 1.5.3.

When I try run the autoxtrabackup.py code to make the incremental backup, occurrs the issue below:


[root@ccccc master_backup_script]# python3 ../autoxtrabackup.py -v -l DEBUG --backup
2018-09-21 00:13:49 DEBUG    <pid.PidFile object at 0x7f5268228548> entering setup
2018-09-21 00:13:49 DEBUG    <pid.PidFile object at 0x7f5268228548> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.py.pid
2018-09-21 00:13:49 DEBUG    <pid.PidFile object at 0x7f5268228548> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.py.pid
2018-09-21 00:13:49 DEBUG    Running mysqladmin command -> /usr/bin/mysqladmin --defaults-file=/etc/my.cnf --user=backup_user --password='*' status --host=127.0.0.1 --port=3306
2018-09-21 00:13:49 DEBUG    OK: Server is Up and running
2018-09-21 00:13:49 DEBUG    OK: /usr/bin/mysql exists
2018-09-21 00:13:49 DEBUG    OK: /usr/bin/mysqladmin exists
2018-09-21 00:13:49 DEBUG    OK: MySQL configuration file exists
2018-09-21 00:13:49 DEBUG    OK: XtraBackup exists
2018-09-21 00:13:49 DEBUG    OK: Main backup directory exists
2018-09-21 00:13:49 DEBUG    OK: Full Backup directory exists
2018-09-21 00:13:49 DEBUG    OK: Increment directory exists
2018-09-21 00:13:49 DEBUG    OK: Check status
2018-09-21 00:13:49 DEBUG    - - - - You have a full backup that is less than 604800.0 seconds old. - - - -
2018-09-21 00:13:49 DEBUG    - - - - We will take an incremental one based on recent Full Backup - - - -
2018-09-21 00:13:52 DEBUG    <pid.PidFile object at 0x7f5268228548> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.py.pid
Traceback (most recent call last):
  File "../autoxtrabackup.py", line 308, in <module>
    all_procedure()
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "../autoxtrabackup.py", line 266, in all_procedure
    b.all_backup()
  File "/home/MySQL-AutoXtraBackup/master_backup_script/backuper.py", line 917, in all_backup
    self.inc_backup()
  File "/home/MySQL-AutoXtraBackup/master_backup_script/backuper.py", line 815, in inc_backup
    logger.debug("The following backup command will be executed {}".format(filteredargs))
UnboundLocalError: local variable 'filteredargs' referenced before assignment
2018-09-21 00:13:52 DEBUG    <pid.PidFile object at 0x7f5268228548> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.py.pid
[root@dubhe master_backup_script]# vi backuper.py
[root@dubhe master_backup_script]# python3 ../autoxtrabackup.py -version
Error: no such option: -e
[root@dubhe master_backup_script]# python3 ../autoxtrabackup.py --version
Developed by Shahriyar Rzayev from Azerbaijan MUG(http://mysql.az)
Link : https://github.com/ShahriyarR/MySQL-AutoXtraBackup
Email: rzayev.shahriyar@yandex.com
Based on Percona XtraBackup: https://github.com/percona/percona-xtrabackup/
MySQL-AutoXtraBackup Version: 1.5.3
