### ISSUE TITLE
error while running backup command

### ISSUE THREAD

**Issue by bimith** [ShahriyarR/MySQL-AutoXtraBackup#386]

**Comment by bimith** [comment]
[root@soldier datastore_1]# cd /else/xb_test/server_dir/
[root@soldier server_dir]# vim bck.cnf
[root@soldier server_dir]# autoxtrabackup --backup --tag=" Full backup" -v -l DEBUG -lf /else/xb_test/backup_dir/xb.log --defaults-file=/else/xb_test/server_dir/bck.cnf
2020-03-12 13:37:59 DEBUG    <pid.PidFile object at 0x7fa9180545c8> entering setup
2020-03-12 13:37:59 DEBUG    <pid.PidFile object at 0x7fa9180545c8> create pidfile: /else/tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2020-03-12 13:37:59 DEBUG    <pid.PidFile object at 0x7fa9180545c8> check pidfile: /else/tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2020-03-12 13:37:59 DEBUG    Running mysqladmin command -> /usr/bin/mysqladmin --defaults-file=/etc/my_1.cnf --user=mysqlbackup --password='*'@123' status --socket=/else/datastore_1/mysql.sock
2020-03-12 13:37:59 ERROR    FAILED: Server is NOT Up
2020-03-12 13:37:59 CRITICAL FAILED: Check status
2020-03-12 13:37:59 ERROR    FAILED: Server is NOT Up
2020-03-12 13:37:59 DEBUG    <pid.PidFile object at 0x7fa9180545c8> closing pidfile: /else/tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.4-py3.5.egg/general_conf/check_env.py", line 201, in check_all_env
    self.check_mysql_uptime()
  File "/usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.4-py3.5.egg/general_conf/check_env.py", line 58, in check_mysql_uptime
    raise RuntimeError('FAILED: Server is NOT Up')
RuntimeError: FAILED: Server is NOT Up

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.5.4', 'console_scripts', 'autoxtrabackup')()
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/Click-7.0-py3.5.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.4-py3.5.egg/autoxtrabackup.py", line 275, in all_procedure
    b.all_backup()
  File "/usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.4-py3.5.egg/master_backup_script/backuper.py", line 774, in all_backup
    if check_env_obj.check_all_env():
  File "/usr/local/lib/python3.5/site-packages/mysql_autoxtrabackup-1.5.4-py3.5.egg/general_conf/check_env.py", line 213, in check_all_env
    raise RuntimeError("FAILED: Check status")
RuntimeError: FAILED: Check status
2020-03-12 13:37:59 DEBUG    <pid.PidFile object at 0x7fa9180545c8> closing pidfile: /else/tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid


kindly help me 
here i have used remote db server ip
db is running in another server, i have changed the inside cnf file  
dear sacko please help me

**Comment by bimith** [comment]
anybody help me

**Comment by JasperAlgra** [comment]
@bimith man.. take it easy on the tickets please.
