### ISSUE TITLE
While we are trying to install using by source getting keep on error mysql-connector-python even installed the same package--without internet how we can install suggest me please

### ISSUE THREAD

**Issue by bimith** [ShahriyarR/MySQL-AutoXtraBackup#394]
Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    @_call_aside
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3236, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3265, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'mysql-connector==2.1.4' distribution was not found and is required by mysql-autoxtrabackup

kindly help me

**Comment by ShahriyarR** [comment]
You should get the master branch(latest release) and install it using `python3 setup.py install` command.
