### ISSUE TITLE
error while using --partial

### ISSUE THREAD

**Issue by ahmedovemin** [ShahriyarR/MySQL-AutoXtraBackup#4]
[root@emin home]# autoxtrabackup --partial
    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
    Type Database name: lkgfd
    Type Table name: sdfnl
    Sorry, There is no such Database or Table in backup directory
    Or maybe table storage engine is not InnoDB
    Traceback (most recent call last):
      File "/usr/local/bin/autoxtrabackup", line 9, in <module>
    load_entry_point('mysql-autoxtrabackup==1.0', 'console_scripts', 'autoxtrabackup')()
      File "/usr/local/lib/python3.3/site-packages/click-4.0-py3.3.egg/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
      File "/usr/local/lib/python3.3/site-packages/click-4.0-py3.3.egg/click/core.py", line 644, in main
    rv = self.invoke(ctx)
      File "/usr/local/lib/python3.3/site-packages/click-4.0-py3.3.egg/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/lib/python3.3/site-packages/click-4.0-py3.3.egg/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
      File "/usr/local/lib/python3.3/site-packages/mysql_autoxtrabackup-1.0-py3.3.egg/autoxtrabackup.py", line 39, in all_procedure
      File "/usr/local/lib/python3.3/site-packages/mysql_autoxtrabackup-1.0-py3.3.egg/partial_recovery/partial.py", line 323, in final_actions
    TypeError: 'bool' object is not subscriptable

**Comment by ShahriyarR** [comment]
Thank you for report.
Yes, this exception comes up, when there is no existing database or table in backup directory.

**Comment by ShahriyarR** [comment]
Fixed as described:
-------------------------
Added check for file path of .frm file.
Thank you for report.
