### ISSUE TITLE
Testing fails - report them here

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#416]
```
# autoxtrabackup --backup 
Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==2.0', 'console_scripts', 'autoxtrabackup')()
  File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click-7.1.2-py3.6.egg/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/mysql_autoxtrabackup-2.0-py3.6.egg/autoxtrabackup.py", line 186, in all_procedure
AttributeError: 'GeneralClass' object has no attribute 'log_file_max_bytes'
```

**Comment by ShahriyarR** [comment]
TODO:
add fallback=None to all optional arguments in config file.

**Comment by ShahriyarR** [comment]
Logger fails as:

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 936, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/handlers.py", line 857, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

```

**Comment by m7mdcc** [comment]
Hii @ShahriyarR  ,

How to solve this ?  AttributeError: 'GeneralClass' object has no attribute 'log_file_max_bytes'
Even i have log_file_max_bytes in my config

**Comment by ShahriyarR** [comment]
Hi @m7mdcc sorry for the late reply, I am on vacation currently.
So this error should be fixed by this PR -> https://github.com/ShahriyarR/MySQL-AutoXtraBackup/pull/417

But on the way, I got new errors and due to this, I have postponed merging. I will try to come back here again - also please keep in mind that these changes are for release version - 2.0  and this will be the most mature version of this tool.
Stay tuned. If you wish to contribute please feel free to check out the release_v2.0 branch and start testing it.

**Comment by ShahriyarR** [comment]
I found time to play a bit now and the new logical issue is that after refactoring the backup streaming functionality seems to be broken.
TODO: figure out why the streaming options were ignored and why the streaming itself did not raise the error.

**Comment by ShahriyarR** [comment]
closing for now. need to go further with release v2.0 branch.
