### ISSUE TITLE
UnboundLocalError: local variable 'args' referenced before assignment

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#45]
```
sudo autoxtrabackup --backup -v -l DEBUG --defaults_file=/home/shahriyar.rzaev/AutoXtrabackup_Configs/ps_5.7_master_bck.conf
<pid.PidFile object at 0x7fdc15fa50e8> entering setup
<pid.PidFile object at 0x7fdc15fa50e8> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7fdc15fa50e8> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Running mysqladmin command -> /home/shahriyar.rzaev/Percona_Servers/5.7.17/bin/mysqladmin --defaults-file=/home/shahriyar.rzaev/sandboxes/rsandbox_Percona-Server-5_7_17/master/my.sandbox.cnf --user=jeffrey --password=msandbox status --host=localhost --port=20192
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
/home/shahriyar.rzaev/Percona_Servers/5.7.17/bin/mysql exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-OK
/home/shahriyar.rzaev/Percona_Servers/5.7.17/bin/mysqladmin exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
MySQL configuration file exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+OK
Xtrabackup exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-OK
Main backup directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-OK
Full Backup directory exists.+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+OK
Increment directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
Check status: STATUS+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-+-+-OK
################################################################
You have a full backup that is less than 86400 seconds old. - -#
We will take an incremental one based on recent Full Backup - -#
################################################################
mysqladmin ver command Failed
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at 'localhost' failed
error: 'Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)'
Check that mysqld is running and that the socket: '/tmp/mysql.sock' exists!
<pid.PidFile object at 0x7fdc15fa50e8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.5', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/autoxtrabackup.py", line 160, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/master_backup_script/backuper.py", line 594, in all_backup
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/master_backup_script/backuper.py", line 327, in inc_backup
UnboundLocalError: local variable 'args' referenced before assignment
<pid.PidFile object at 0x7fdc15fa50e8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

**Comment by ShahriyarR** [comment]
Seems to be the problem is in `check_env.check_mysql_product` function
