### ISSUE TITLE
Error if you have single quote in password like 'Pas12345

### ISSUE THREAD

**Issue by Komport** [ShahriyarR/MySQL-AutoXtraBackup#49]
I am using Mysql 5.7.16
Password parameter in /etc/bck.cnf defined as below.
mysql_password='Pas12345

Command
```
./autoxtrabackup --backup -v -l DEBUG
```

Error log.
```
[root@server bin]# ./autoxtrabackup --backup -v -l DEBUG
<pid.PidFile object at 0x7f9b7fc33048> entering setup
<pid.PidFile object at 0x7f9b7fc33048> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7f9b7fc33048> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Running mysqladmin command -> /usr/bin/mysqladmin --defaults-file=/etc/my.cnf --user=root --password='Pas12345 status --host=127.0.0.1 --port=3306
<pid.PidFile object at 0x7f9b7fc33048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "./autoxtrabackup", line 9, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.5', 'console_scripts', 'autoxtrabackup')()
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/autoxtrabackup.py", line 160, in all_procedure
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/master_backup_script/backuper.py", line 509, in all_backup
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/general_conf/check_env.py", line 384, in check_all_env
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/general_conf/check_env.py", line 36, in check_mysql_uptime
  File "/opt/Python-3.5.3/lib/python3.5/shlex.py", line 273, in split
    return list(lex)
  File "/opt/Python-3.5.3/lib/python3.5/shlex.py", line 263, in __next__
    token = self.get_token()
  File "/opt/Python-3.5.3/lib/python3.5/shlex.py", line 90, in get_token
    raw = self.read_token()
  File "/opt/Python-3.5.3/lib/python3.5/shlex.py", line 166, in read_token
    raise ValueError("No closing quotation")
ValueError: No closing quotation
<pid.PidFile object at 0x7f9b7fc33048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid

```

Then I enclosed password with double quotes like below.
```
mysql_password="'Pas12345"
```

As you can see I got error during connecting to mysql instance.
```
[root@rtpdbs bin]# ./autoxtrabackup --backup -v -l DEBUG
<pid.PidFile object at 0x7f10fab07048> entering setup
<pid.PidFile object at 0x7f10fab07048> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7f10fab07048> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Running mysqladmin command -> /usr/bin/mysqladmin --defaults-file=/etc/my.cnf --user=root --password="'My162636@" status --host=127.0.0.1 --port=3306
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at '127.0.0.1' failed
error: 'Host '127.0.0.1' is not allowed to connect to this MySQL server'
Server is NOT Up+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
<pid.PidFile object at 0x7f10fab07048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7f10fab07048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
[root@rtpdbs bin]# vi /etc/bck.conf
[root@rtpdbs bin]# ./autoxtrabackup --backup -v -l DEBUG
<pid.PidFile object at 0x7f09a1ef9048> entering setup
<pid.PidFile object at 0x7f09a1ef9048> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7f09a1ef9048> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Running mysqladmin command -> /usr/bin/mysqladmin --defaults-file=/etc/my.cnf --user=root --password="'Pass12345" status --host=localhost --port=3306
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
/usr/bin/mysql exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-OK
/usr/bin/mysqladmin exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
MySQL configuration file exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+OK
Xtrabackup exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-OK
Main backup directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-OK
Full Backup directory does not exist.+-+-+-+-+-+-+-+-+-+-+-+-OK
Creating full backup directory...+-+-+-+-+-+-+-+-+-++-+-+-+-+OK
Created+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
Increment directory does not exist.+-+-+-+-+-+-+-+-+-++-+-+-+OK
Creating increment backup directory.+-+-+-+-+-+-+-+-+-++-+-+-OK
Created
Check status: STATUS+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-+-+-OK
###############################################################
#You have no backups : Taking very first Full Backup! - - - - #
###############################################################
Trying to flush logs
Log flushing completed
The following backup command will be executed /usr/bin/xtrabackup --defaults-file=/etc/my.cnf --user=root --password='"'Pas12345"'  --target-dir=/backup/full/2017-02-17_11-51-26 --backup --host=localhost --port=3306
Starting /usr/bin/xtrabackup
FULL BACKUP FAILED!
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
<pid.PidFile object at 0x7f09a1ef9048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7f09a1ef9048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid

```
But tool trying to take backup and failed. Because it is adding another single quotes.

**Comment by ShahriyarR** [comment]
Thanks for report.
Why you got this error?

```
Running mysqladmin command -> /usr/bin/mysqladmin --defaults-file=/etc/my.cnf --user=root --password="'My162636@" status --host=127.0.0.1 --port=3306
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
mysqladmin: connect to server at '127.0.0.1' failed
error: 'Host '127.0.0.1' is not allowed to connect to this MySQL server'
```

**Comment by Komport** [comment]
Because of host parameter. Later i have changed to localhost.

**Comment by ShahriyarR** [comment]
So this is not related to the tool. right?
The only thing I am curious about where the extra quotes came from.

**Comment by Komport** [comment]
I did not understand this part.
```
Trying to flush logs
Log flushing completed
```
If tool cant connect to the system how it did Flush logs?

**Comment by ShahriyarR** [comment]
Well from last output you pasted, I see, that it is connected successfully:

```
[root@rtpdbs bin]# ./autoxtrabackup --backup -v -l DEBUG
<pid.PidFile object at 0x7f09a1ef9048> entering setup
<pid.PidFile object at 0x7f09a1ef9048> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7f09a1ef9048> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Running mysqladmin command -> /usr/bin/mysqladmin --defaults-file=/etc/my.cnf --user=root --password="'Pass12345" status --host=localhost --port=3306
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
/usr/bin/mysql exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-OK
/usr/bin/mysqladmin exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
MySQL configuration file exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+OK
Xtrabackup exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-OK
Main backup directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-OK
Full Backup directory does not exist.+-+-+-+-+-+-+-+-+-+-+-+-OK
Creating full backup directory...+-+-+-+-+-+-+-+-+-++-+-+-+-+OK
Created+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
Increment directory does not exist.+-+-+-+-+-+-+-+-+-++-+-+-+OK
Creating increment backup directory.+-+-+-+-+-+-+-+-+-++-+-+-OK
Created
Check status: STATUS+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-+-+-OK
###############################################################
#You have no backups : Taking very first Full Backup! - - - - #
###############################################################
Trying to flush logs
Log flushing completed
The following backup command will be executed /usr/bin/xtrabackup --defaults-file=/etc/my.cnf --user=root --password='"'Pas12345"'  --target-dir=/backup/full/2017-02-17_11-51-26 --backup --host=localhost --port=3306
Starting /usr/bin/xtrabackup
FULL BACKUP FAILED!
/bin/sh: -c: line 0: unexpected EOF while looking for matching `"'
/bin/sh: -c: line 1: syntax error: unexpected end of file
<pid.PidFile object at 0x7f09a1ef9048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7f09a1ef9048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

Actually the xtrabackup failed to connect but mysqladmin as well as mysql client coulld connect there.

**Comment by Komport** [comment]
So, problem only with single quotes.
