### ISSUE TITLE
ValueError: unconverted data remains

### ISSUE THREAD

**Issue by Komport** [ShahriyarR/MySQL-AutoXtraBackup#51]
if we rename full backup directory name or create dummy folder under full directory.
Renamed folder
```
[root@server full]# ll
total 4
drwxr-xr-x 6 root root 4096 Feb 17 14:47 2017-02-17_14-23-01_old

```
Backup command
```
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
/usr/bin/mysql exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-OK
/usr/bin/mysqladmin exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
MySQL configuration file exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+OK
Xtrabackup exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-OK
Main backup directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-OK
Full Backup directory exists.+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+OK
Increment directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
Check status: STATUS+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-+-+-OK
<pid.PidFile object at 0x7f6b16345048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/opt/Python-3.5.3/bin/autoxtrabackup", line 9, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.5', 'console_scripts', 'autoxtrabackup')()
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/autoxtrabackup.py", line 160, in all_procedure
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/master_backup_script/backuper.py", line 540, in all_backup
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/master_backup_script/backuper.py", line 53, in last_full_backup_date
  File "/opt/Python-3.5.3/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/opt/Python-3.5.3/lib/python3.5/_strptime.py", line 346, in _strptime
    data_string[found.end():])
ValueError: unconverted data remains: _old
<pid.PidFile object at 0x7f6b16345048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid

```
With dummy folder
```
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
/usr/bin/mysql exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-OK
/usr/bin/mysqladmin exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
MySQL configuration file exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+OK
Xtrabackup exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-OK
Main backup directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-OK
Full Backup directory exists.+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+OK
Increment directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
Check status: STATUS+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-+-+-OK
<pid.PidFile object at 0x7f0bab490048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/opt/Python-3.5.3/bin/autoxtrabackup", line 9, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.5', 'console_scripts', 'autoxtrabackup')()
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/autoxtrabackup.py", line 160, in all_procedure
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/master_backup_script/backuper.py", line 540, in all_backup
  File "/opt/Python-3.5.3/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/master_backup_script/backuper.py", line 53, in last_full_backup_date
  File "/opt/Python-3.5.3/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/opt/Python-3.5.3/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data 'test' does not match format '%Y-%m-%d_%H-%M-%S'
```

**Comment by Komport** [comment]
But if you run prepare command it will work as expected.
```
[root@server 2017-02-17_14-23-01_old]# autoxtrabackup --prepare -v -l DEBUG
<pid.PidFile object at 0x7fda422da048> entering setup
<pid.PidFile object at 0x7fda422da048> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7fda422da048> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Installed Server is MySQL, will continue as usual.
There is no /usr/lib/systemd/system folder, Continue
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-

Preparing full/inc backups!
What do you want to do?
1. Prepare Backups and keep for future usage. NOTE('Once Prepared Backups Can not be prepared Again')
2. Prepare Backups and restore/recover/copy-back immediately
3. Just copy-back previously prepared backups
Please Choose one of options and type 1 or 2 or 3: 1

+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
####################################################################################################
You have Incremental backups. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -#
Preparing Full backup 1 time. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -#
Final prepare,will occur after preparing all inc backups - - - - - - - - - - - - - - - - -  - - - -#
####################################################################################################
Running prepare command -> /usr/bin/xtrabackup --prepare --apply-log-only --target-dir=/backup/full/2017-02-17_14-23-01_old
0217 14:46:57 completed OK!
####################################################################################################
Preparing Incs:
####################################################################################################
Preparing last incremental backup, inc backup dir/name is 2017-02-17_14-25-11
####################################################################################################
Running prepare command -> /usr/bin/xtrabackup --prepare --target-dir=/backup/full/2017-02-17_14-23-01_old --incremental-dir=/backup/inc/2017-02-17_14-25-11
0217 14:47:20 completed OK!
####################################################################################################
The end of the Prepare Stage. - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -#
####################################################################################################
<pid.PidFile object at 0x7fda422da048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
<pid.PidFile object at 0x7fda422da048> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```
