### ISSUE TITLE
TypeError: expected string or bytes-like object; /bin/sh: /usr/bin/mysqlfrm: No such file or directory

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#56]
The result of run:

```
[shahriyar.rzaev@qaserver-04 MySQL-AutoXtraBackup]$ sudo autoxtrabackup --partial -v -l DEBUG --defaults_file=/home/shahriyar.rzaev/AutoXtrabackup_Configs/ps_5.7_master_bck.conf
2017-02-21 15:16:38 DEBUG    <pid.PidFile object at 0x7f661748ff48> entering setup
2017-02-21 15:16:38 DEBUG    <pid.PidFile object at 0x7f661748ff48> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-02-21 15:16:38 DEBUG    <pid.PidFile object at 0x7f661748ff48> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-02-21 15:16:38 DEBUG    +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
Type Database name: dbtest
Type Table name: t1
2017-02-21 15:16:50 DEBUG    Running mysqladmin command -> /home/shahriyar.rzaev/Percona_Servers/5.7.17/bin/mysqladmin --defaults-file=/home/shahriyar.rzaev/sandboxes/rsandbox_Percona-Server-5_7_17/master/my.sandbox.cnf --user=jeffrey --password=msandbox status --host=localhost --port=20192
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
2017-02-21 15:16:50 DEBUG    Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
2017-02-21 15:16:50 DEBUG    Checking if innodb_file_per_table is enabled
2017-02-21 15:16:50 DEBUG    Will run following command ->/home/shahriyar.rzaev/Percona_Servers/5.7.17/bin/mysql --defaults-file=/home/shahriyar.rzaev/sandboxes/rsandbox_Percona-Server-5_7_17/master/my.sandbox.cnf -ujeffrey --password=msandbox --host=localhost --port=20192 -e "select @@global.innodb_file_per_table"
2017-02-21 15:16:51 DEBUG    innodb_file_per_table is enabled!
2017-02-21 15:16:51 DEBUG    Checking MySQL version
2017-02-21 15:16:51 DEBUG    MySQL Version is, 5.7.17-11-log
2017-02-21 15:16:51 DEBUG    You have correct version of MySQL
2017-02-21 15:16:51 DEBUG    Checking if database exists in MySQL
2017-02-21 15:16:51 ERROR    There is no such database!
2017-02-21 15:16:51 ERROR    Create Specified Database in MySQL Server, before restoring single table
We can create it for you do you want? (yes/no): yes
2017-02-21 15:16:57 DEBUG    Creating specified database
2017-02-21 15:16:57 DEBUG    dbtest database created
2017-02-21 15:16:57 DEBUG    Checking if table exists in MySQL Server
2017-02-21 15:16:57 ERROR    Table does not exist in MySQL Server.
2017-02-21 15:16:57 ERROR    You can not restore table, with not existing tablespace file(.ibd)!
2017-02-21 15:16:57 ERROR    We will try to extract table create statement from .frm file, from backup folder
2017-02-21 15:16:57 DEBUG    Running mysqlfrm tool
2017-02-21 15:16:57 ERROR    Failed
2017-02-21 15:16:57 ERROR    /bin/sh: /usr/bin/mysqlfrm: No such file or directory
2017-02-21 15:16:57 DEBUG    <pid.PidFile object at 0x7f661748ff48> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.5', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/autoxtrabackup.py", line 168, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/partial_recovery/partial.py", line 374, in final_actions
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.5-py3.5.egg/partial_recovery/partial.py", line 182, in check_table_exists_on_mysql
TypeError: expected string or bytes-like object
2017-02-21 15:16:57 DEBUG    <pid.PidFile object at 0x7f661748ff48> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

**Comment by ShahriyarR** [comment]
So the check for `mysqlfrm` tool should be added, before starting partial recovery procedures.

**Comment by ShahriyarR** [comment]
Seems to be fixed:

```
sudo autoxtrabackup --partial -v -l DEBUG --defaults_file=/home/shahriyar.rzaev/AutoXtrabackup_Configs/ps_5.7_master_bck.conf
2017-02-21 17:17:53 DEBUG    <pid.PidFile object at 0x7f0286e690e8> entering setup
2017-02-21 17:17:53 DEBUG    <pid.PidFile object at 0x7f0286e690e8> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-02-21 17:17:53 DEBUG    <pid.PidFile object at 0x7f0286e690e8> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-02-21 17:17:53 CRITICAL Could not find mysqlfrm! Please install it or check if it is in PATH
2017-02-21 17:17:53 CRITICAL Aborting!
2017-02-21 17:17:53 DEBUG    <pid.PidFile object at 0x7f0286e690e8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-02-21 17:17:53 DEBUG    <pid.PidFile object at 0x7f0286e690e8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```
