### ISSUE TITLE
AttributeError: 'Backup' object has no attribute 'archive_dir'; if backup is timedout

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#72]
```
$ sudo autoxtrabackup --backup -v -l DEBUG --defaults_file=/home/shahriyar.rzaev/AutoXtrabackup_Configs/ps_5.7_master_bck.conf
2017-02-27 08:58:11 DEBUG    <pid.PidFile object at 0x7fee2db010e8> entering setup
2017-02-27 08:58:11 DEBUG    <pid.PidFile object at 0x7fee2db010e8> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-02-27 08:58:11 DEBUG    <pid.PidFile object at 0x7fee2db010e8> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-02-27 08:58:11 DEBUG    Running mysqladmin command -> /home/shahriyar.rzaev/Percona_Servers/5.7.17/bin/mysqladmin --defaults-file=/home/shahriyar.rzaev/sandboxes/rsandbox_Percona-Server-5_7_17/master/my.sandbox.cnf --user=jeffrey --password=msandbox status --host=localhost --port=20192
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
2017-02-27 08:58:12 DEBUG    Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
2017-02-27 08:58:12 DEBUG    /home/shahriyar.rzaev/Percona_Servers/5.7.17/bin/mysql exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-OK
2017-02-27 08:58:12 DEBUG    /home/shahriyar.rzaev/Percona_Servers/5.7.17/bin/mysqladmin exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
2017-02-27 08:58:12 DEBUG    MySQL configuration file exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+OK
2017-02-27 08:58:12 DEBUG    Xtrabackup exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-OK
2017-02-27 08:58:12 DEBUG    Main backup directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-OK
2017-02-27 08:58:12 DEBUG    Full Backup directory exists.+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+OK
2017-02-27 08:58:12 DEBUG    Increment directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
2017-02-27 08:58:12 DEBUG    Check status: STATUS+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-+-+-OK
2017-02-27 08:58:12 DEBUG    ################################################################
2017-02-27 08:58:12 DEBUG    Your full backup is timeout : Taking new Full Backup!- - - - - #
2017-02-27 08:58:12 DEBUG    ################################################################
2017-02-27 08:58:15 DEBUG    <pid.PidFile object at 0x7fee2db010e8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.6', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.6-py3.5.egg/autoxtrabackup.py", line 160, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_xtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.6-py3.5.egg/master_backup_script/backuper.py", line 549, in all_backup
AttributeError: 'Backup' object has no attribute 'archive_dir'
2017-02-27 08:58:15 DEBUG    <pid.PidFile object at 0x7fee2db010e8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```

**Comment by ShahriyarR** [comment]
Seems to be fixed:

```
$ sudo autoxtrabackup --backup -v -l DEBUG --defaults_file=/home/shahriyar.rzaev/AutoXtrabackup_Configs/ps_5.7_master_bck.conf
2017-03-03 14:02:04 DEBUG    <pid.PidFile object at 0x7f9372f8b0e8> entering setup
2017-03-03 14:02:04 DEBUG    <pid.PidFile object at 0x7f9372f8b0e8> create pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-03-03 14:02:04 DEBUG    <pid.PidFile object at 0x7f9372f8b0e8> check pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-03-03 14:02:04 DEBUG    Running mysqladmin command -> /home/shahriyar.rzaev/Percona_Servers/5.7.17/bin/mysqladmin --defaults-file=/home/shahriyar.rzaev/sandboxes/rsandbox_Percona-Server-5_7_17/master/my.sandbox.cnf --user=jeffrey --password=msandbox status --host=localhost --port=20192
mysqladmin: [Warning] Using a password on the command line interface can be insecure.
2017-03-03 14:02:04 DEBUG    Server is Up and running+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+OK
2017-03-03 14:02:04 DEBUG    /home/shahriyar.rzaev/Percona_Servers/5.7.17/bin/mysql exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-++-OK
2017-03-03 14:02:04 DEBUG    /home/shahriyar.rzaev/Percona_Servers/5.7.17/bin/mysqladmin exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
2017-03-03 14:02:04 DEBUG    MySQL configuration file exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+OK
2017-03-03 14:02:04 DEBUG    Xtrabackup exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-OK
2017-03-03 14:02:04 DEBUG    Main backup directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-OK
2017-03-03 14:02:04 DEBUG    Full Backup directory exists.+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+OK
2017-03-03 14:02:04 DEBUG    Increment directory exists+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-OK
2017-03-03 14:02:04 DEBUG    Check status: STATUS+-+-+-+-+-+-+-+-+-++-+-+-+-+-+-+-+-+-+-+-OK
2017-03-03 14:02:04 DEBUG    ################################################################
2017-03-03 14:02:04 DEBUG    Your full backup is timeout : Taking new Full Backup!- - - - - #
2017-03-03 14:02:04 DEBUG    ################################################################
2017-03-03 14:02:07 DEBUG    Archiving disabled. Skipping!
2017-03-03 14:02:07 DEBUG    Trying to flush logs
2017-03-03 14:02:07 DEBUG    Log flushing completed
2017-03-03 14:02:07 DEBUG    The following backup command will be executed /home/shahriyar.rzaev/Percona_Xtrabackups/xb_2.4/usr/local/xtrabackup/bin/xtrabackup --defaults-file=/home/shahriyar.rzaev/sandboxes/rsandbox_Percona-Server-5_7_17/master/my.sandbox.cnf --user=jeffrey --password='msandbox'  --target-dir=/home/shahriyar.rzaev/backup_dirs/ps_5.7_master//full/2017-03-03_14-02-07 --backup --host=localhost --port=20192 --compress=quicklz --compress-chunk-size=65536 --compress-threads=4 --encrypt=AES256 --encrypt-key='VVTBwgM4UhwkTTV98fhuj+D1zyWoA89K' --encrypt-threads=4 --encrypt-chunk-size=65536
2017-03-03 14:02:07 DEBUG    Starting /home/shahriyar.rzaev/Percona_Xtrabackups/xb_2.4/usr/local/xtrabackup/bin/xtrabackup
2017-03-03 14:02:20 DEBUG    0303 14:02:20 completed OK!
2017-03-03 14:02:20 DEBUG    <pid.PidFile object at 0x7f9372f8b0e8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
2017-03-03 14:02:20 DEBUG    <pid.PidFile object at 0x7f9372f8b0e8> closing pidfile: /tmp/MySQL-AutoXtraBackup/autoxtrabackup.pid
```
