### ISSUE TITLE
AttributeError: 'Backup' object has no attribute ‘myuseroption’

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#9]
Reported using mail:

I’m trying to configure and run MySQL-AutoXtraBackup on Percona Cluster.

At this stage, I have already installed AutoXtraBackup:

```
sudo /opt/Python-3.3.2/bin/autoxtrabackup --help
Usage: autoxtrabackup [OPTIONS]

Options:
  --prepare  Prepare/recover backups.
  --backup   Take full and incremental backups.
  --partial  Recover specified table (partial recovery).
  --version  Version information.
  --help     Show this message and exit.

```

```
sudo /opt/Python-3.3.2/bin/autoxtrabackup --version
Developed by Shahriyar Rzayev from Azerbaijan MUG(http://mysql.az)
Link : https://github.com/ShahriyarR/MySQL-AutoXtraBackup
Email: rzayev.shahriyar@yandex.com
Based on Percona XtraBackup: https://launchpad.net/percona-xtrabackup
MySQL-AutoXtrabackup Version 1.0

```

When I run the first Backup:

```
# autoxtrabackup --backup
Traceback (most recent call last):
  File "/usr/local/bin/autoxtrabackup", line 9, in <module>
    load_entry_point('mysql-autoxtrabackup==1.0', 'console_scripts', 'autoxtrabackup')()
  File "/usr/local/lib/python3.4/dist-packages/click-6.2-py3.4.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/click-6.2-py3.4.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.4/dist-packages/click-6.2-py3.4.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.4/dist-packages/click-6.2-py3.4.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mysql_autoxtrabackup-1.0-py3.4.egg/autoxtrabackup.py", line 34, in all_procedure
  File "/usr/local/lib/python3.4/dist-packages/mysql_autoxtrabackup-1.0-py3.4.egg/master_backup_script/backuper.py", line 32, in __init__
AttributeError: 'Backup' object has no attribute ‘myuseroption’

```

I would appreciate very much your help, to figure it out what the problem is.

Thank you

**Comment by ShahriyarR** [comment]
Fixed as:
 ```
class Backup(GeneralClass):
-    def __init__(self):
+    def __init__(self, *args, **kwargs):
 
 
-        #GeneralClass.__init__(self)
+        GeneralClass.__init__(self, *args, **kwargs)

```
