### ISSUE TITLE
Remove MariaDB specific checks from tool as it is also makes a noise; do the copy-back stage ready to use

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#92]
There is currently no need to apply workarounds for MariaDB specific things inside the code.
The workaround options can be supplied from config file and it is much more convenient way.

**Comment by ShahriyarR** [comment]
Also this report is related:
https://github.com/ShahriyarR/MySQL-AutoXtraBackup/issues/91

**Comment by ShahriyarR** [comment]
```
$ autoxtrabackup --backup -v -l DEBUG --defaults_file=./AutoXtrabackup_Configs/new_ps_5.6.conf
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.8', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/autoxtrabackup.py", line 144, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/autoxtrabackup.py", line 96, in validate_file
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/autoxtrabackup.py", line 80, in check_file_content
KeyError: "Mandatory key 'systemd_start_mysql' doesn't exists in ./AutoXtrabackup_Configs/new_ps_5.6.conf."
```

**Comment by ShahriyarR** [comment]
With full backup, it is prepared and copied back successfully.

```
2017-07-19 09:19:53 DEBUG    ####################################################################################################
2017-07-19 09:19:53 DEBUG    Shutting Down MySQL server: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -#
2017-07-19 09:19:53 DEBUG    ####################################################################################################
2017-07-19 09:19:56 DEBUG    
2017-07-19 09:19:56 DEBUG    ####################################################################################################
2017-07-19 09:19:56 DEBUG    Moving MySQL datadir to /tmp/mysql: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -#
2017-07-19 09:19:56 DEBUG    ####################################################################################################
2017-07-19 09:19:59 DEBUG    Moved datadir to /tmp/mysql ...
2017-07-19 09:19:59 DEBUG    Creating an empty data directory ...
2017-07-19 09:19:59 DEBUG    Datadir is Created! ...
2017-07-19 09:19:59 DEBUG    ####################################################################################################
2017-07-19 09:19:59 DEBUG    Copying Back Already Prepared Final Backup: - - - - - - - - - - - - - - - - - - - - - - - - - - - -#
2017-07-19 09:19:59 DEBUG    ####################################################################################################
2017-07-19 09:20:15 DEBUG    ####################################################################################################
2017-07-19 09:20:15 DEBUG    Data copied back successfully! - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - #
2017-07-19 09:20:15 DEBUG    ####################################################################################################
2017-07-19 09:20:18 DEBUG    ####################################################################################################
2017-07-19 09:20:18 DEBUG    New copied-back data now owned by specified user! - - - - - - - - - - - - - - - - - - - - - - - - - - -#
2017-07-19 09:20:18 DEBUG    ####################################################################################################
2017-07-19 09:20:18 DEBUG    ####################################################################################################
2017-07-19 09:20:18 DEBUG    Starting MySQL/MariaDB server: 
2017-07-19 09:20:18 DEBUG    ####################################################################################################
2017-07-19 09:20:22 DEBUG    Starting MySQL ...
2017-07-19 09:20:22 DEBUG    . sandbox server started
2017-07-19 09:20:22 DEBUG    ####################################################################################################
2017-07-19 09:20:22 DEBUG    All data copied back successfully your MySQL server is UP again. 
Congratulations. 
Backups are life savers
2017-07-19 09:20:22 DEBUG    ####################################################################################################
```

**Comment by ShahriyarR** [comment]
Incremental backup taking failed as:

```
2017-07-19 09:24:08 DEBUG    ################################################################
2017-07-19 09:24:08 DEBUG    You have a full backup that is less than 86400 seconds old. - -#
2017-07-19 09:24:08 DEBUG    We will take an incremental one based on recent Full Backup - -#
2017-07-19 09:24:08 DEBUG    ################################################################
2017-07-19 09:24:11 DEBUG    <pid.PidFile object at 0x7f9b0e94a2c8> closing pidfile: /home/shahriyar.rzaev/backup_dir/autoxtrabackup.pid
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/autoxtrabackup", line 11, in <module>
    load_entry_point('mysql-autoxtrabackup==1.4.8', 'console_scripts', 'autoxtrabackup')()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/click-6.7-py3.5.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/autoxtrabackup.py", line 164, in all_procedure
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/master_backup_script/backuper.py", line 735, in all_backup
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/mysql_autoxtrabackup-1.4.8-py3.5.egg/master_backup_script/backuper.py", line 303, in inc_backup
AttributeError: 'CheckEnv' object has no attribute 'check_mysql_product'
```

**Comment by ShahriyarR** [comment]
Another fail:

```
2017-07-19 10:34:03 DEBUG    ####################################################################################################
2017-07-19 10:34:03 DEBUG    Moving MySQL datadir to /tmp/mysql: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -#
2017-07-19 10:34:03 DEBUG    ####################################################################################################
2017-07-19 10:34:06 ERROR    Error occurred while moving datadir
2017-07-19 10:34:06 ERROR    Destination path '/tmp/data' already exists
```
