### ISSUE TITLE
Implement some features XtraBackup for test purposes as part of --test_mode

### ISSUE THREAD

**Issue by ShahriyarR** [ShahriyarR/MySQL-AutoXtraBackup#99]
The plan is:
* To have some --test_mode option to enable XtraBackup test run
* This is not intended to be used in production
* The main submodules for preparing environment:

-- To get Percona Server from github[repo link or branch etc. can be passed from commandline/config file]. - DONE
-- To build PS server it in debug mode. - DONE
-- To start demo server. - DONE
-- To run sample sysbench run against this started server. - DONE

* The main submodules for backup process:
-- We have already this functionalities where we can pass options to xtrabackup, we can take backup and recover it. But for test purposes, it needs to be done automatically. I.e start PS + take backup + recover + check if recovered correctly, or check if there is problem or not.

**Comment by ShahriyarR** [comment]
These subtasks can be separately created as small issues and implemented in that way.

**Comment by ShahriyarR** [comment]
We have some improvement here:

```
$ python -m pytest -s -vvv test_prepare_env_test.py
========================================================================== test session starts ==========================================================================
platform linux -- Python 3.5.3, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/python
cachedir: ../.cache
rootdir: /home/shahriyar.rzaev/MySQL-AutoXtraBackup, inifile:
collected 3 items                                                                                                                                                        

test_prepare_env_test.py::TestBackupTestMode::test_clone_percona_qa PASSED
test_prepare_env_test.py::TestBackupTestMode::test_clone_ps_server_from_conf PASSED
```

**Comment by ShahriyarR** [comment]
The last one remaining is sysbench run:

```
$ python -m pytest -s -vvv ~/MySQL-AutoXtraBackup/test/test_prepare_env_test.py
========================================================================== test session starts ==========================================================================
platform linux -- Python 3.5.3, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/python
cachedir: MySQL-AutoXtraBackup/.cache
rootdir: /home/shahriyar.rzaev/MySQL-AutoXtraBackup, inifile:
collected 5 items                                                                                                                                                        

MySQL-AutoXtraBackup/test/test_prepare_env_test.py::TestBackupTestMode::test_clone_percona_qa PASSED
MySQL-AutoXtraBackup/test/test_prepare_env_test.py::TestBackupTestMode::test_clone_ps_server_from_conf PASSED
MySQL-AutoXtraBackup/test/test_prepare_env_test.py::TestBackupTestMode::test_build_server PASSED
MySQL-AutoXtraBackup/test/test_prepare_env_test.py::TestBackupTestMode::test_prepare_startup PASSED
MySQL-AutoXtraBackup/test/test_prepare_env_test.py::TestBackupTestMode::test_start_server PASSED
```

**Comment by ShahriyarR** [comment]
Failed tests:

```
$ python -m pytest -s -vvv ~/MySQL-AutoXtraBackup/test/test_run_benchmark.py
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/_pytest/config.py", line 342, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/shahriyar.rzaev/MySQL-AutoXtraBackup/test/test_run_benchmark.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/_pytest/config.py", line 342, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/shahriyar.rzaev/MySQL-AutoXtraBackup/test')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/_pytest/config.py", line 373, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/shahriyar.rzaev/MySQL-AutoXtraBackup/test/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/_pytest/config.py", line 379, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/py/_path/local.py", line 662, in pyimport
    __import__(modname)
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 212, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/shahriyar.rzaev/MySQL-AutoXtraBackup/test/conftest.py", line 16, in <module>
    rb_obj = RunBenchmark()
  File "/home/shahriyar.rzaev/MySQL-AutoXtraBackup/prepare_env_test_mode/run_benchmark.py", line 15, in __init__
    self.basedir = CloneBuildStartServer.get_basedir(self.testpath)
  File "/home/shahriyar.rzaev/MySQL-AutoXtraBackup/prepare_env_test_mode/clone_build_start_server.py", line 68, in get_basedir
    status, output = subprocess.getstatusoutput(cmd.format(self.testpath))
AttributeError: 'str' object has no attribute 'testpath'
ERROR: could not load /home/shahriyar.rzaev/MySQL-AutoXtraBackup/test/conftest.py
```

**Comment by ShahriyarR** [comment]
Interesting fail here:

```
$ python -m pytest -s -vvv ~/MySQL-AutoXtraBackup/test/test_run_benchmark.py
========================================================================== test session starts ==========================================================================
platform linux -- Python 3.5.3, pytest-3.2.3, py-1.4.34, pluggy-0.4.0 -- /home/shahriyar.rzaev/virtualenvs/py_3_5_3_autoxtrabackup/bin/python
cachedir: MySQL-AutoXtraBackup/.cache
rootdir: /home/shahriyar.rzaev/MySQL-AutoXtraBackup, inifile:
collected 4 items                                                                                                                                                        

MySQL-AutoXtraBackup/test/test_run_benchmark.py::TestRunBenchmark::test_get_sock FAILED
MySQL-AutoXtraBackup/test/test_run_benchmark.py::TestRunBenchmark::test_get_mysql_conn PASSED
MySQL-AutoXtraBackup/test/test_run_benchmark.py::TestRunBenchmark::test_create_db PASSED
MySQL-AutoXtraBackup/test/test_run_benchmark.py::TestRunBenchmark::test_run_sysbench FAILED

=============================================================================== FAILURES ================================================================================
____________________________________________________________________ TestRunBenchmark.test_get_sock _____________________________________________________________________

self = <test.test_run_benchmark.TestRunBenchmark object at 0x7f82e57d7438>
return_run_benchmark_obj = <prepare_env_test_mode.run_benchmark.RunBenchmark object at 0x7f82e5798940>

    def test_get_sock(self, return_run_benchmark_obj):
>       assert "-S" in return_run_benchmark_obj.get_sock()

MySQL-AutoXtraBackup/test/test_run_benchmark.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <prepare_env_test_mode.run_benchmark.RunBenchmark object at 0x7f82e5798940>

    def get_sock(self):
        # Get socket connection path from PS basedir
        sock_cmd = "cat {}/cl_noprompt_nobinary | awk '{print $4}'"
>       status, output = subprocess.getstatusoutput(sock_cmd.format(self.basedir))
E       KeyError: 'print $4'

MySQL-AutoXtraBackup/prepare_env_test_mode/run_benchmark.py:20: KeyError
```

**Comment by ShahriyarR** [comment]
So as all listed features implemented properly, we can close this issue and go on.
Will create new release branch and will release new version after full implementation.
